### ISSUE TITLE
[Feature request] audio scope

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#102]
Работа методов audio недоступна публично для всех методов КРОМЕ загрузки аудио с устройства, который продолжает быть доступен при наличии пользовательского токена с scope:audio . Но это невозможно сделать так как в MiniApps нет возможность получить токен с соответствующими правами.

Добавьте, пожалуйста, audio в список допустимых scope при получении токена. Это всё равно не позволит использовать ограниченные методы audio, так как там ограничение на уровне типа токена, но позволит использовать загрузку audio (https://vk.com/dev/upload_files_2?f=8.%2BЗагрузка%2Bаудиозаписей).

**Comment by ilyapishchulin** [comment]
Вернемся, если поймем, что нужно

**Comment by KSmokvin** [comment]
Опишу наш кейс:
Наше мини-приложение (app7297645), одобренное и размещённое в каталоге, работает с приёмом предложенных постов в сообществах, заменяя стандартную форму из одного поля на структурированную форму с множеством настраиваемых полей.

При этом нам необходимо предоставить возможность пользователям прикреплять к предлагаемым постам аудиозаписи, чтобы наша форма не уступала в возможностях стандартной форме. Множество пользователей просит добавить прикрепление аудио, из-за чего не могут полноценно перейти к использованию мини-приложения в сообществе

audio scope закрыт для публичного использования. В целом причины этого понятны. Но стандартное API Вконтакте содержит два публичных НЕОГРАНИЧЕННЫХ метода для audio - audio.getUploadServer и audio.save -которые позволили бы нам реализовать хотя бы минимум - ручную загрузку прикрепляемых к посту аудио с устройства. Но на стороне мини-приложения не получается использовать эти разрешённые методы, так как на стороне мини-приложений нет технической возможности получить токен пользователя с правами audio.

Если добавить в мини приложения поддержку audio токена - разработчики всё равно не смогут использовать не-публичные методы аудио. Но смогут (на равное со стандартным API) использовать audio.getUploadServer и audio.save - что в частности нам позволит прикреплять аудио к предлагаемому посту.

_Или, если есть такая возможность, мы были бы очень благодарны, если бы нам предоставили доступ к audio в индивидуальном порядке. Наше приложение не рассчитано на то, чтобы сохранять или воспроизводить аудиозаписи внутри приложения, а только лишь прикреплять аудио к постам, которые в дальнейшем публикуются на стене сообществ стандартным образом._

**Comment by ilyapishchulin** [comment]
Посмотрим

**Comment by ilyapishchulin** [comment]
К сожалению, scope audio выдавать не будем
