### ISSUE TITLE
Ошибка при отправке VKWebAppSetViewSettings

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#103]
На изменение `VKWebAppSetViewSettings`:
```js
bridge.send('VKWebAppSetViewSettings', {
  status_bar_style: 'light',
  action_bar_color: '#355FDE',
  navigation_bar_color: '#537EF9'
});
```
приходит `VKWebAppSetViewSettingsFailed` с 
```js
error_code: 5
error_reason: "Invalid params"
error_type: "client_error"
```
хотя все устанавливается нормально.

Android 10
VK 6.2
vk-bridge 2.2.0

**Comment by ilyapishchulin** [comment]
Не воспроизвелось, актуально?

**Comment by eolme** [comment]
Воспроизводится.
![Screenshot_20200729-193840](https://user-images.githubusercontent.com/11076888/88821020-265aa200-d1d3-11ea-9eaf-d2aa39fcaabc.png)

**Comment by ilyapishchulin** [comment]
А если попробовать без navigation_bar_color? Мы не анонсировали данный проп

**Comment by eolme** [comment]
В типах есть, оно работает некорректно, мне не важно, что анонсировано оно или нет.

**Comment by ilyapishchulin** [comment]
Логично, что если оно не указано в документации, то и использовать его не стоит. 

Без него всё корректно работает?

**Comment by eolme** [comment]
Логично, если оно не работает - надо исправить?

**Comment by kuhel** [comment]
> В типах есть, оно работает некорректно, мне не важно, что анонсировано оно или нет.

Ок, выпилим из типов

**Comment by ilyapishchulin** [comment]
Исправлено, проверите?

**Comment by ilyapishchulin** [comment]
Видимо нет
