### ISSUE TITLE
Прозрачный экшн-бар

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#104]
Как он работает, или точнее как он должен работать?
В документации к `VKWebAppSetViewSettings` написано, что можно установить значение `none`, что сделает его прозрачным. Однако фактически он становится просто черным.

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by eolme** [comment]
Поправили, но не в лучшую сторону, открою новый issue
