### ISSUE TITLE
[Feature request] Метод для получения текущего конфига

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/vk-bridge#109]
На данный момент в бридже присутствует возможность конфиг (который приходит в событии `VKWebAppUpdateConfig`) только "услышать", то есть, отследить при помощи listener'ов. Это сводится к тому, что появляется неявная проблема с тем, что чтобы получить этот конфиг, необходимо знать те случаи, когда он отправляется - сразу после `VKWebAppInit` и при фокусе на инпуте (и наверняка есть еще какие-то кейсы о которых я не знаю).

В связи с этим, предлагаю добавить метод, который позволял бы этот конфиг просто взять и получить не костыляя при этом listener'ами и не давая возможному багу связанному с тем, что listener был добавлен уже после того, как отправлено событие, быть.

Например - `VKWebAppGetConfig`.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Done
