### ISSUE TITLE
[Feature request] Метод для отказа от сообщений группы

### ISSUE THREAD

**Issue by heyqbnk** [VKCOM/vk-bridge#111]
Сейчас существует метод для разрешения сообщений (`VKWebAppAllowMessagesFromGroup`) от группы, но отказаться от них возможности нет. Всё усугубляется тем, что чтобы отказаться от сообщений, необходимо тогда использовать `VKWebAppCallAPIMethod`, но он требует `access_token` со scope `messages`, который в большинстве приложений получить просто нельзя (необходимо проходить модерацию). В итоге попадаем в ситуацию где пользователь не может отказаться от сообщений, но может принять.

Предлагаемое название - `VKWebAppDenyMessagesFromGroup`.

**Comment by ilyapishchulin** [comment]
Передал
