### ISSUE TITLE
После разблокировки экрана не приходит VKWebAppViewRestore

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#113]
На iOS не приходит событие:
<img src="https://user-images.githubusercontent.com/11076888/83371376-64099d00-a3d3-11ea-8078-d09e6d5c7f5c.png" height="320" />
На Android приходит:
<img src="https://user-images.githubusercontent.com/11076888/83371474-9adfb300-a3d3-11ea-91fd-20f7b603a994.png" height="320" />

**Comment by ilyapishchulin** [comment]
Пришел VKWebAppViewHide

**Comment by eolme** [comment]
Не приходит.

**Comment by ilyapishchulin** [comment]
Давай разбираться, в этом приложении есть события, которые априори убираются. (В настройках глянь)

**Comment by eolme** [comment]
Спасибо, я ведь не знаю как им пользоваться.

**Comment by ilyapishchulin** [comment]
У тебя тестовая сборка? Я еще раз проверил и всё приходит.

**Comment by eolme** [comment]
Только что проверил

iPhone SE (старый)
iOS 13.5.1

**Comment by eolme** [comment]
VKWebAppViewHide приходит, VKWebAppViewRestore нет

**Comment by ilyapishchulin** [comment]
Restore тоже приходит, попросил проверить тестировщика

**Comment by ilyapishchulin** [comment]
Исправлено в сборке для тестеров.

**Comment by eolme** [comment]
Я не тестировщик - переоткрывайте или создаю новое.

**Comment by ilyapishchulin** [comment]
Исправлено, проверите?
