### ISSUE TITLE
Не отображается платёжка на Android

### ISSUE THREAD

**Issue by Eshvengel** [VKCOM/vk-bridge#114]
Добрый день!
Подключаем библиотеку через "dist/index.umd.js" и вызываем метод "VKWebAppShowOrderBox", на Android в приложении не отображается окно подтверждения для тестового платежа. Платёж совершается автоматически, судя по логам. 
Если пробовать совершить покупку через m.vk.com, окно подтверждения (Купить/Отменить) отображается как надо.

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Закрываю из-за отсутствия активности
