### ISSUE TITLE
На iOS приходит VKWebAppViewHide при открытии шторок

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#115]
Событие `VKWebAppViewHide` используется, чтобы понять, когда приложение закрыто. Например, это позволяет остановить фоновую музыку, корректно завершить некие длящиеся процессы.

При этом кратковременная потеря фокуса, такая, как открытие шторки на iOS, останавливать работу приложения не должна. Но на iOS при этом приложению прилетает событие `VKWebAppViewHide`.

Возможные пути решения:
* Не отправлять событие `VKWebAppViewHide` при открытии шторки
* Отправлять событие `VKWebAppViewHide` с дополнительными параметрами, которые говорят, было ли приложение закрыто целиком, или фокус потерян временно

**Comment by ilyapishchulin** [comment]
Такова жизнь iOS

**Comment by eolme** [comment]
Проблема не исправлена, переоткрывайте или открываю новый issue.

**Comment by eolme** [comment]
Игнорирование и закрытие issue - не решение проблемы.
