### ISSUE TITLE
[Feature request] Метод перезагрузки приложения

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#116]
Пожелание: сделать метод, который позволяет вызывать перезагрузку фрейма. Использование `window.location.reload()` с этой целью вызывает проблемы.

Юзкейс:
У приложения из-за плохого интернета не подгрузились какие-то важные статические ресурсы (графика, шрифты, стили), и приложение способно это понять, высвечивает плашку "Проблемы с интернетом" и кнопкой "Попробовать ещё раз".

**Comment by ilyapishchulin** [comment]
Привет, мы обсудили твое ишью, спасибо

Ты должен сам вызывать перерисовку приложения, а если что-то не загрузилось, то сделать это вручную
Так можно стрелять самому себе в ногу, пока не будет.

Если решим снова обсудить такую идею -- отпишусь тут
