### ISSUE TITLE
Некорректная работа VKWebAppGetGeodata

### ISSUE THREAD

**Issue by IlyaSteik** [VKCOM/vk-bridge#118]
Если приложению "ВКонтакте" отклонить доступ к геоданным, то никакое событие от vk-bridge не придёт.
Проблему можно наблюдать на видео - https://vk.com/video245481845_456240569

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Закрываю из-за отсутствия активности
