### ISSUE TITLE
Не отправляется событие VKWebAppShowStoryBox при выходе из кеша

### ISSUE THREAD

**Issue by d-a-m** [VKCOM/vk-bridge#119]
Столкнулся с проблемой отправки события VKWebAppShowStoryBox после возврата в приложения из кеша. У промиса bridge.send("VKWebAppShowStoryBox", {...}) не срабатывает ни then, ни catch, ни final и именно в ситуации, когда приложение восстановилось из кеша и перед этим событие отправлялось.

Детальные шаги воспроизведения в отчёте тестировщика: https://vk.com/bug238326.

Если кеш очищен, то событие отправляется, редактор историй открывается.

**Comment by PavelMartinez** [comment]
Воспроизводится

**Comment by wolframdeus** [comment]
Скажите, проблема воспроизводится только на Андроиде или на IOS тоже?

**Comment by d-a-m** [comment]
Воспроизводится на обоих ОС. на Андройде проверял лично, на iOS слов тестировщиков.

**Comment by wolframdeus** [comment]
Попробуйте, пожалуйста, на Андроиде закрыть приложение через крестик справа вверху и попробовать снова вызвать событие `VKWebAppShowStoryBox`. Скорее всего, оно не должно сработать. Отпишитесь как только попробуете

**Comment by PavelMartinez** [comment]
так и есть

**Comment by d-a-m** [comment]
> Попробуйте, пожалуйста, на Андроиде закрыть приложение через крестик справа вверху и попробовать снова вызвать событие `VKWebAppShowStoryBox`. Скорее всего, оно не должно сработать. Отпишитесь как только попробуете

Два сценария. **Первый**:

1. Зайти в приложение;
2. Нажать на крестик
3. Повторно зайти в приложение отправить событие VKWebAppShowStoryBox -- **редактор историй открывается**


**Второй**.

1. Зайти в приложение;
2. Отправить событие VKWebAppShowStoryBox -- **редактор историй открывается**, закрыть редактор/отправить сторис
4. Нажать на крестик
5. Повторно зайти в приложение отправить событие VKWebAppShowStoryBox -- **редактор историй НЕ открывается**

**Comment by ilyapishchulin** [comment]
https://github.com/VKCOM/vk-bridge/issues/122
Следите за развитием тут
