### ISSUE TITLE
Получение базовой информации о сообществе

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/vk-bridge#12]
Добрый день, можно ли получить базовую информацию о сообществе у приложения установленного **в сообщество**? Я имею в виду аналог метода `VKWebAppGetUserInfo`

**Comment by danakt** [comment]
Метод `VKWebAppGetUserInfo` возвращает информацию о пользователе, который работает с приложением, а не любого. 

Вы можете использовать метод `VKWebAppCallAPIMethod` для вызова метода основного API

**Comment by mahnunchik** [comment]
@danakt да, `VKWebAppGetUserInfo` возвращает базовые данные текущего пользователя, что очень удобно, так как полезно при отображении аккаунта пользователя без запросов к API.

Было бы удобно, аналогично этому методу получить базовую информацию сообщества **в которое установлено приложение**.

Например вот приложение установленное в сообщество: https://vk.com/avia.tips?mid=-147923770

С помощью базовой информации и о сообществе и о пользователе можно было бы отобразить приветствие такое как: `Дешёвые авиабилеты и туры из Новосибирска (OVB) приветствуют Ивана Петрова`.

Если я правильно понял, то с помощью метода `VKWebAppCallAPIMethod` мне сначала необходимо запросить токен до доступа к группам  `groups` и только потом получить информацию о сообществе. Что является излишним для приветствия и базовой информации о сообществе.

**Comment by danakt** [comment]
@mahnunchik можно рассмотреть эту идею, но пока вы можете использовать вышеуказанный метод. Токен берётся вами из настроек приложения, запрашивать ничего не требуется, вы просто делаете запрос 🙂

**Comment by mahnunchik** [comment]
@danakt спасибо, да, на стороне сервера могу так запросить данные. Но будет также удобно и на стороне приложения ;)

**Comment by mahnunchik** [comment]
@kuhel не будет базовой информации о сообществе запустившего приложение?

**Comment by danakt** [comment]
@mahnunchik будет в обозримом будущем

**Comment by mahnunchik** [comment]
Ваще кайф!

**Comment by danakt** [comment]
@mahnunchik пока не на всех платформах реализовано, будет всё доступно в ближайшее время
