### ISSUE TITLE
Не приходит событие VKWebAppLocationChanged в клиенте ВК

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/vk-bridge#121]
Исходные данные:
Платформа: iOS
Версия ВК приложения: 6.6.3
Версия iOS: 13.3.1
Версия vk-bridge: 2.2.2

Не срабатывает подписка на событие *VKWebAppLocationChanged*.

Кейс:
Когда пользователь заходит в уже загруженное в кэш приложение с новым хэшом в адресной строке, или же если програмно менять хэш событием *VKWebAppSetLocation*, ни в одном из этих случаев на представленной платформе событие не вызывается. В случае браузера все работает отлично.

**Comment by b-ponomarenko** [comment]
В случае необходимости могу записать видео с демонстранцией

**Comment by wolframdeus** [comment]
@b-ponomarenko Да, запишите, пожалуйста видео с воспроизведенным багом. На Андроиде пробовали?

**Comment by b-ponomarenko** [comment]
На андроиде тоже не приходит событие.

PC: https://gofile.io/d/YdJ7IG
Android: https://gofile.io/d/xjkjiR

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by eolme** [comment]
Воспроизводится

**Comment by ilyapishchulin** [comment]
<img width="726" alt="Снимок экрана 2020-07-30 в 11 30 40" src="https://user-images.githubusercontent.com/45998835/88900495-1c2eb700-d258-11ea-91b6-08b0d7a432d7.png">
