### ISSUE TITLE
Промисы ломаются когда приложение уходит в кэш.

### ISSUE THREAD

**Issue by gbowsky** [VKCOM/vk-bridge#122]
Исходные данные:
Платформа: Android
Версия ВК приложения: 6.7 (5620)
Версия Android: 10.0 (Q)
Версия vk-bridge: 2.2.2

Когда сервис уходит в кэш, любой Promise в состоянии "pending" просто исчезает, что приводит к бесконечным загрузкам внутри мини-приложений после восстановления из кэша. Найти способ отловить это на данный момент не удалось и проблема касается большинства мини-приложений находящихся в VK Mini Apps.

Ниже примеры сервисов, в которых мне удалось воспроизвести эту проблему. (Скриншоты)
<details> 
  <summary>Эко Просто</summary>

   ![image](https://user-images.githubusercontent.com/36237725/86818573-388f6780-c08f-11ea-8f69-5ff0d7fd8685.png)
</details>
<details> 
  <summary>Беседы</summary>

   ![image](https://user-images.githubusercontent.com/36237725/86818597-3d541b80-c08f-11ea-825d-3bd2fd9147ad.png)
</details>
<details> 
  <summary>CultureMap</summary>

   ![image](https://user-images.githubusercontent.com/36237725/86818604-404f0c00-c08f-11ea-82b2-91874d2039fb.png)
</details>
<details> 
  <summary>Quizer</summary>

   ![image](https://user-images.githubusercontent.com/36237725/86818610-42b16600-c08f-11ea-987d-1ea2cf891c52.png)
</details>
<details> 
  <summary>Макдоналдс</summary>

   ![image](https://user-images.githubusercontent.com/36237725/86818625-4644ed00-c08f-11ea-9a19-7338c878adbf.png)
</details>

**Comment by wolframdeus** [comment]
Будет круто, если проверите, воспроизводится ли эта проблема на iOS

**Comment by gbowsky** [comment]
На iOS данная проблема не воспроизводится.

**Comment by gbowsky** [comment]
Не воспроизводится
Видео с демонстрацией проблемы: [Android](https://youtu.be/WXlFFjjuv7g)
[iOS](https://youtu.be/WaeLHUGYMxc)

**Comment by gbowsky** [comment]
Также отмечу, что на iOS постоянно сбрасывается (при очистке кэша и даже перезапуске клиента) VK Storage, который на Android сбросить вовсе невозможно.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by NekR** [comment]
Fixed
