### ISSUE TITLE
Не работает событие VKWebAppCopyText в браузере

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/vk-bridge#123]
При попытке вызвать событие VKWebAppCopyText в браузере копирование не происходит. iOS 14, Safari

**Comment by ilyapishchulin** [comment]
VKWebAppCopyText не работает в браузере

**Comment by ExLineP** [comment]
@mainsmirnov VKWebAppCopyText не работает на всех устройствах. Все остальные методы bridge работают. Скорее всего потому что в iframe не передано разрешение на копирование в буфер обмена.

![image](https://github.com/VKCOM/vk-bridge/assets/12397836/229df44a-4c50-4a03-8c5a-cfeadc61d30a)

**Comment by sharipovv** [comment]
> @mainsmirnov VKWebAppCopyText не работает на всех устройствах. Все остальные методы bridge работают. Скорее всего потому что в iframe не передано разрешение на копирование в буфер обмена.
> 
> ![image](https://private-user-images.githubusercontent.com/12397836/325976810-229df44a-4c50-4a03-8c5a-cfeadc61d30a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzUxNzYsIm5iZiI6MTcxNDEzNDg3NiwicGF0aCI6Ii8xMjM5NzgzNi8zMjU5NzY4MTAtMjI5ZGY0NGEtNGM1MC00YTAzLThjNWEtY2ZlYWRjNjFkMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyMzQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNmNkZTA5ZTRjOTU2NmUzNTgzNmZkM2UxN2IwYzQ1OGJjYmRjOTA3ZjQ3OWNjNjQ1YTgxNDU5M2I5NDJiNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ef1u-6nQRa4jaTHPLUx7FhOLUNlwDELCC74TyY8YDOs)

Привет! Получится поделиться ссылкой на пример? Пока что не удалось воспроизвести проблему: https://vk.com/test_vkapp#share_hDZMhT191o
