### ISSUE TITLE
В Android-клиенте нет доступа к камере

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#126]
**Шаги воспроизведения**
* Использовать `<input type="file" accept="image/*"/>`
* Открыть приложение в Android-клиенте
* Нажать на выбор файла

**Ожидаемое поведение**
Открывается меню выбора "Сделать фото или Галерея".
Сейчас так происходит на iOS-клиенте и в m.vk

**Фактическое поведение**
Открывается только выбор из файлов, без доступа к камере.

**Где убедиться**
Приложение [QR-конструктор](https://vk.com/app6899379). Выбрать "С фоном" и нажать на кнопку камеры.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Исправили, спасибо за issue
