### ISSUE TITLE
[Feature Request] Добавить событие загрузки изображения на сервера ВК

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#128]
Если приложению нужна просто прямая ссылка на изображение, то сейчас такая загрузка проходит с использованием альбома стены во много этапов:
1. Получение токена с нужным scope
2. Вызов метода `getWallUploadServer`
3. Загрузка изображения на **свой сервер** из-за кроссдоменной политики
4. Загрузка изображения со своего сервера на сервер ВК
5. Вызов метода `saveWallPhoto`

Предлагаю добавить событие, в которое можно будет передать файл изображения, а на выходе получить прямой url с этим изображением, загруженным на сервера ВК. По аналогии с тем, как работает API сервиса Imgur.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by Pronin-vk** [comment]
Спасибо за обращение, рассмотрели в команде платформы, пока не планируем реализовывать данный функционал.
