### ISSUE TITLE
[Feature] Сделать возможность создания чата

### ISSUE THREAD

**Issue by arizorin** [VKCOM/vk-bridge#129]
Было бы неплохо реализовать хотя бы возможность создания диалогов и отправки сообщений (метод api Message). Это позволит не плодить разработчикам диалоги внутри мини эпов и будет намного приятнее с точки зрения пользования сервиса.

**Comment by ilyapishchulin** [comment]
Какой смысл в этом? 

Можно создать беседу на стороне сервера и в клиенте пользователю нажать ссылку типа vk.me/joinxxxx.
Можно аналогично направлять на сообщения сообщества или пользователя по ссылкам: vk.me/club1 vk.me/id1
