### ISSUE TITLE
Событие VKWebAppShowImages на Android открывает несколько окон

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#130]
**Шаги воспроизведения:**
1. Написать код, который выполняет несколько вызовов `VKWebAppShowImages` подряд с одинаковым `url`.
2. Открыть приложение с этим кодом на Android

**Фактическое поведение**
Открывается много окон с одинаковыми фотографиями 

**Ожидаемое поведение**
Вызовы `VKWebAppShowImages` игнорируются до тех пор, пока не закрыто текущее окно с фотографией.
ИЛИ
Новое окно с фотографией открывается вместо старого.

**Юзкейс**
На медленных телефонах пользователи жмут кнопку открытия фотографий несколько раз подряд, и из-за этого происходит несколько вызовов события.

**Comment by ilyapishchulin** [comment]
Нужно дизейблить кнопку, чтобы не было возможности на нее нажать.

**Comment by DenisNP** [comment]
@ilyapishchulin прочитайте внимательно описание, пожалуйста. На медленных устройствах окно открывается медленно, и пользователь может нажать на кнопку много раз. На каком основании её дизейблить, когда придёт событие Hide? Оно тоже придёт с задержкой. Или её дизейблить на 5 секунд сразу после нажатия? Это костыль.

**Comment by ilyapishchulin** [comment]
Можно отображать лоадер до успешного результата. Во всяком случае мы подумаем над проблемой

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
