### ISSUE TITLE
Добавить mVK в метод VKWebAppGetClientVersion

### ISSUE THREAD

**Issue by epexa** [VKCOM/vk-bridge#132]
Добавьте пожалуйста **mVK** в результат метода [VKWebAppGetClientVersion](https://vk.com/dev/vk_bridge_events_3?f=%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8%20%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F).

Это например нужно когда отличается реализация мобильной веб-версии от десктопной. _Например реализация фотогалереи в ВК отличается в веб-версии и обычной, поэтому чтобы в VK Mini App реализовать подобное, необходимо получить это значение._

**Comment by eolme** [comment]
Так платформу можно получить из параметров url

**Comment by epexa** [comment]
> Так платформу можно получить из параметров url

Ладно, раз это сложно...

Пусть останется это здесь:
```js
const urlParams = new URLSearchParams(window.location.search);
const platform = urlParams.get('vk_platform');
```

**Comment by ilyapishchulin** [comment]
Так работает же, нет?

**Comment by epexa** [comment]
> Так работает же, нет?

Да, добавили "**mobile-web**" !

![image](https://user-images.githubusercontent.com/2198826/88804538-a89d9300-d1e0-11ea-96da-73cba0759426.png)

**Comment by ilyapishchulin** [comment]
Отлично)
