### ISSUE TITLE
Не функционирует метод VKWebAppStorageSet после восстановления сервиса из кэша.

### ISSUE THREAD

**Issue by PavelMartinez** [VKCOM/vk-bridge#133]
По аналогии с #119, если восстановить сервис из кэша и попробовать вызвать VKWebAppStorageSet, ничего не произойдёт. Причём не происходит ни resolve, ни reject.

**Comment by ilyapishchulin** [comment]
https://github.com/VKCOM/vk-bridge/issues/122
