### ISSUE TITLE
[Bug] Прозрачный statusbar/navbar

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#138]
В документации к `VKWebAppSetViewSettings` написано, что можно установить значение `none`, что сделает statusbar прозрачным. Однако фактически viewport расширяется за пределы экрана - под statusbar и под navbar. Если с statusbar можно просто добавить padding в 24px (стандартная высота), то вот с navbar ничего нельзя сделать, т.к. при передаче прозрачного цвета вида `#AARRGGBB`, фон под ним остается черным.

**Comment by ilyapishchulin** [comment]
Заведено

**Comment by ilyapishchulin** [comment]
Исправлено, проверите?

**Comment by ilyapishchulin** [comment]
Видимо, не актуально
