### ISSUE TITLE
[Bug] Событие VKWebAppShowQR

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#139]
- Не задокументировано
- Promise не резолвится

**Comment by ilyapishchulin** [comment]
Оно не актуально.

https://vk.com/dev/vk_bridge_events_3?f=Сканирование%20QR-кода

**Comment by eolme** [comment]
`Show`, а не `Open`

**Comment by eolme** [comment]
Игнорирование и закрытие issue - не решение проблемы
