### ISSUE TITLE
[Vulnerability] Многократное событие VKWebAppShowNativeAds

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#142]
Есть возможность многократно вызывать полноэкранную рекламу, которая полностью блокирует интерфейс тем, что забивает историю и нет возможности закрыть мини приложение.

**Comment by ilyapishchulin** [comment]
За такое блокируем.

**Comment by eolme** [comment]
Проблема не исправлена, переоткрывайте или открываю новый issue.

**Comment by eolme** [comment]
Игнорирование и закрытие issue - не решение проблемы

**Comment by kuhel** [comment]
Ок, рассмотрим варианты ограничений вызова подобных событий

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
