### ISSUE TITLE
[Bug] После разблокировки экрана не приходит VKWebAppViewRestore

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#145]
Переоткрыл, проблема не исправлена.

See: #113

**Comment by ilyapishchulin** [comment]
Дождись релиза сборки. Если не будет работать -- опишись в том ишью.
Мне приходят уведомления, я зачему

**Comment by eolme** [comment]
@ilyapishchulin, вы конечно можете делать что угодно, однако issue не закрывают просто так - пока проблема не решена, не важно в тестировании, в бэклоге, или где либо ещё что-то сделали, issue отображает текущее состояние. Как только изменения станут публичными - тогда и только тогда нужно закрывать issue.

**Comment by ilyapishchulin** [comment]
Открыл ради твоего спокойствия. Другие пока закрыты правильно.
