### ISSUE TITLE
[Bug] Не работает VKWebAppSetLocation

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#147]
На Android не работает событие `VKWebAppSetLocation`

**Comment by eolme** [comment]
Событие об успехе приходит, но `hash` не меняется

**Comment by ilyapishchulin** [comment]
Запиши видео с такими шагами, пожалуйста:
1. Вызови событие VKWebAppSetLocation с location: 'test'
2. Нажми на три точки справа сверху.
3. Поделиться -> любой диалог.
4. Открой ссылку из диалога.

**Comment by eolme** [comment]
![Screenshot_20200730-121506](https://user-images.githubusercontent.com/11076888/88898814-5602bc00-d25e-11ea-8054-aa2838ca3dd1.png)

**Comment by ilyapishchulin** [comment]
Проверил тут: https://vk.com/app6703670
При нативном шаринге всё отображается.
Версия из стора. Попробуй через window

**Comment by eolme** [comment]
Это и есть window

**Comment by eolme** [comment]
https://vk.com/app7415273

**Comment by ilyapishchulin** [comment]
Будем смотреть, hash появляется на ссылке vk.com/appXXX#here

**Comment by stels-cs** [comment]
Кажется window.location.hash и не должен меняться при вызове VKWebAppSetLocation
в window.location.hash мы сами из js кода можем менять как угодно, VKWebAppSetLocation нужен нам чтобы установить "внешний" хеш, в браузере это будет адресная строка (там где vk.com/app13123#12312), в мобилке ссылка для диалога шаринга который вызывается из трех точечек (сверху справа)

**Comment by ilyapishchulin** [comment]
Мы обсудили это и решим чуть позже как лучше поступать

**Comment by eolme** [comment]
Тогда смысл этого события?
В шаринге через событие hash добавить не проблема, а то, что меняется внешний - это Side Effect. Как раз интуитивно понятно, зачем нужен `VKWebAppSetLocation` - меняет везде hash, а не только в url, если бы мы делали это через `location.hash`.

**Comment by ilyapishchulin** [comment]
Прошу прощения за долгое ожидание, обсудили, на данный момент `VKWebAppSetLocation` работает как запланировано. Менять при его вызове location.hash не будем

Спасибо за ишью
