### ISSUE TITLE
[Vulnerability] Многократное событие VKWebAppShowNativeAds

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#148]
Проблема не решена.

Игнорирование - не решение проблемы.
Бездействие - не решение проблемы.
Исправленено в тестовых сборках/отложено/в бэклоге - не решение проблемы.

Issue закрывается только при решении проблемы.

See: #142

**Comment by ilyapishchulin** [comment]
Не стоит такое делать. Последует блокировка рекламы для разработчика навсегда.

**Comment by ilyapishchulin** [comment]
Открыт оригинал
