### ISSUE TITLE
Не корректно отрабатывается параметр запуска vk_is_app_user.

### ISSUE THREAD

**Issue by ArtemSviridov** [VKCOM/vk-bridge#155]
В мобильных приложениях корректно отрабатывается параметр запуска vk_is_app_user. Когда пользователь заходит в приложение в первый раз он равен 0, когда он даёт права, параметр равен 1, когда он отзывает права, удаляя приложение, параметр снова равен 0.

На десктопе же, после удаления приложения vk_is_app_user все равно равен 1. Ну, а исходя из логики мобильных приложений должен быть равен 0.

При тестировании, удалял приложение с Android потом проверял параметр запуска на десктопе, полностью сбрасывая кеш браузера. Для удобства оставил console.log c vk_is_app_user в сервисе [https://vk.com/app6727250](https://vk.com/app6727250)

Я использую vk_is_app_user для того, чтобы понять дал ли пользователь права и могу ли я получить ключ доступа без всплывающего окна. А так как на десктопе баг, приложение не выводит для него велкам панель, а сразу пытается получить ключ доступа, что конечно плохо для пользователя.

Почему именно так? Почему то права доступа на общую информацию никак не обозначаются в параметре запуска vk_access_token_settings, т.е по факту являются null. Вот и получается, что null это и когда нет прав, и когда они есть. Чего конечно в идеале быть не должно.

Создал это ишью по рекомендации агента поддержки. Ссылка на диалог: [https://vk.com/support?act=show&id=36867738](https://vk.com/support?act=show&id=36867738)

**Comment by ilyapishchulin** [comment]
Спасибо за ишью, передал

**Comment by ilyapishchulin** [comment]
Не удалось воспроизвести тему с vk_is_app_user, как сейчас дела?

**Comment by ilyapishchulin** [comment]
Открою ишью как только увижу обратную связь
