### ISSUE TITLE
[Feature Request] Параметр "Ответ на историю" в VKWebAppShowStoryBox

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#156]
Хочется чтобы История, создаваемая через VKWebAppShowStoryBox, могла быть в том числе ответом на другую Историю с заданным id.

**Comment by ilyapishchulin** [comment]
Спасибо, передал

**Comment by Pronin-vk** [comment]
Спасибо за обращение, рассмотрели в команде платформы, пока не планируем реализовывать данный функционал.
