### ISSUE TITLE
Игнорирование части параметров при использовании метода VKWebAppShowWallPostBox на iOS

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#160]
Шаги воспроизведения:
1. На iOS мобильном устройстве вызвать метод VKWebAppShowWallPostBox со следующими параметрами (соответствующими документации wall.post метода):

```
bridge.send("VKWebAppShowWallPostBox", {
owner_id: "-1111111",
from_group: 1,
message: "Тестовый пост",
publish_date: 1609933080,
mark_as_ads:1,
close_comments: 1,
mute_notifications: 1,
copyright: "https://vk.com/wall-192182369_210",
access_token: token,
v: "5.103",
})
```
**Фактический результат:**
- Пост опубликован на стене сообщества сразу, а не добавлен в отложенные
- нет метки "Это реклама"
- комментарии открыты
- оповещение разослано (когда {mark_as_ads:0} - то тоже отсутствует)
- отсутствует источник (когда {mark_as_ads:0} - то тоже отсутствует)

То есть **поля publish_date, mark_as_ads, close_comments, mute_notifications, copyright - полностью проигнорированы** при вызове VKWebAppShowWallPostBox с iOS устройства, в то время как на Андроид устройствах и в веб версии всё работает успешно и в соответствии с документацией метода wall.post

**Ожидаемый результат:**
- Пост добавлен в отложенные, а не опубликован сразу
- есть метка "Это реклама"
- комментарии скрыты
- оповещение не разослано (в случае если {mark_as_ads:0})
- присутствует копирайт (в случае если {mark_as_ads:0})

**Comment by ilyapishchulin** [comment]
Зачем дублировать свой отчет с vk.com/bugs сюда? Мы всё помним

**Comment by KSmokvin** [comment]
Здравствуйте
Вчера соответствующий баг https://vk.com/bug239119 был помечен исправленным закрытым во внутреннем баг трекере вк. Не знаю, рассматриваются ли Вами комментарии в закрытых отчётах, поэтому решил продублировать здесь.

Насколько, я пониманию, с тех пор вышла новая сборка 1045. Но проблема всё ещё **актуальна**. Правда немного изменилась. Теперь при публикации поста с publish_date опцией пост не публикуется на стене сразу, а показывает ошибку.

Подробнее и скриншот здесь: https://vk.com/bug239119?cid=12
