### ISSUE TITLE
Перестаёт работать bridge.send("VKWebAppOpenCodeReader");

### ISSUE THREAD

**Issue by dndrheadof** [VKCOM/vk-bridge#161]
**Шаги воспроизведения:**

1. Вызвать VKWebAppOpenCodeReader и отсканировать код
2. Свернуть мини-приложение
3. Восстановить его из кэша
4. Снова вызвать VKWebAppOpenCodeReader (ничего не открывается, ошибок и результата нигде нет)

**Кусок кода:**
```js
<Button
  before={<Icon28CameraOutline />}
  onClick={() => {
     bridge.send('VKWebAppOpenCodeReader')
  })
  size="xl"
  mode="secondary"
>Сканировать</Button>
```

**Comment by ilyapishchulin** [comment]
Связано с #122
