### ISSUE TITLE
[VKWebAppDownloadFile] Не хватает метода для скачивания файлов под Android

### ISSUE THREAD

**Issue by AdvTechnoKing** [VKCOM/vk-bridge#162]
Нет возможности скачивать файлы из WebView на устройствах под операционной системой Android:

[Видео доказательство](https://vk.com/video_ext.php?oid=102343170&id=456239414&hash=7b1bbd7b1b89194d&hd=2)

Появились кейсы, где разрабы пытаются скачивать файлы.

**Comment by dan0102dan** [comment]
Поддерживаю

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Fixed

**Comment by dan0102dan** [comment]
Возвращает ошибку, если указать в url base64, на IOS скачивается без проблем.
<img width="356" alt="Screen Shot 2020-08-28 at 10 44 02 PM" src="https://user-images.githubusercontent.com/46081038/91609380-00662000-e980-11ea-93b7-c08adbc00436.png">

**Comment by ilyapishchulin** [comment]
Это нужно отдельным тикетом
