### ISSUE TITLE
Не отправляется событие VKWebAppGetPersonalCard при выходе из кеша

### ISSUE THREAD

**Issue by maksimdegtyarev** [VKCOM/vk-bridge#164]
Проблема отправки события VKWebAppGetPersonalCard после очистки кеша. У промиса bridge.send("VKWebAppGetPersonalCard", {...}) не срабатывает ни then, ни catch, ни finally.

Шаги для воспроизведения:
1. Очистить кеш, закрыть mini app и само VK приложение
2. Открыть VK приложение, открыть mini app - VKWebAppGetPersonalCard отправляется
3. Очистить кеш и, не закрывая VK приложение, заново открыть mini app - VKWebAppGetPersonalCard не отправляется

**Comment by ilyapishchulin** [comment]
Какая платформа?

**Comment by maksimdegtyarev** [comment]
> Платформу подскажешь?

Заметил на iOS.

**Comment by maksimdegtyarev** [comment]
Заметил тоже самое поведение у события VKWebAppGetUserInfo. Пробовал его использовать как `bridge.send('VKWebAppGetUserInfo.').then(...)`
и событийным способом
```
bridge.subscribe(e => {
  if (e.detail.type === 'VKWebAppGetUserInfoResult') {
    ...
  }
});

bridge.send('VKWebAppGetUserInfo', {});
```

**Comment by ilyapishchulin** [comment]
Тогда дубликат, увы, спасибо за ишью
#122
