### ISSUE TITLE
Не приходит событие VKWebAppViewHide при сворачивании на Android

### ISSUE THREAD

**Issue by TheYTR** [VKCOM/vk-bridge#171]
Событие не приходит при сворачивании крестиком в правом верхнем углу экрана, однако если свернуть весь клиент ВК, то всё работает должным образом.
<details>
  <summary>Демонстрация</summary>

  ![VkWebAppViewHide](https://user-images.githubusercontent.com/58112106/91147779-31212d80-e6d2-11ea-8971-c18aacc5c736.gif)

</details>

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
