### ISSUE TITLE
VKWebAppViewHide приходит после вызова некоторых событий

### ISSUE THREAD

**Issue by TheYTR** [VKCOM/vk-bridge#172]
После вызова методов VKWebAppOpenCodeReader (android и IOS) и VKWebAppAddToHomeScreen (android) приходит VKWebAppViewHide, что заставляет писать костыли в некоторых кейсах.

<details>
  <summary>Демонстрация</summary> 

![VkWebAppViewHide](https://user-images.githubusercontent.com/58112106/91636256-9a79a700-ea18-11ea-984b-120a5cca5a8c.gif)

</details>

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
