### ISSUE TITLE
VKWebAppShowWallPostBox на различных платформах возвращает строку

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-bridge#174]
Ранее, в #97 была добавлена типизация под это. Теперь эту проблему хотелось бы исправить. Баг лично я замечал только на Android, на других платформах не проверял, но на ПК точно всё ок (число).

**Comment by daniluk4000** [comment]
Я также добавил черновой PR, чтобы не забыли поменять типы после (надеюсь) фикса

**Comment by ilyapishchulin** [comment]
Поправим, спасибо

**Comment by ilyapishchulin** [comment]
Поправили
