### ISSUE TITLE
Не работает загрузка файлов base64 и по абсолютному пути при использовании VKWebAppDownloadFile

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-bridge#175]
Собственно, VKWebAppDownloadFile, кажется, поддерживает только загрузку по полной ссылке, с указанием домена, https и прочего веселья. Однако, это не всегда бывает удобно, особенно если у приложения много версий и, как следствие, доменов.

Загрузка в base64 так же не работает (или я что-то не так делаю?), а это нужно для приложений, где, например, есть генерация картинок с возможностью скачать. 

https://vk.com/app7132256 - вот в этом приложении можно потыкать и протестировать оба этих бага. Ниже прилагаю пример того, как я в этом приложении вызываю метод

```typescript
await this.$connect.send('VKWebAppDownloadFile', {
/**
* require(...) возвращает нечто вида /static/img/story.55f92be.png
* убедиться в этом можно, посмотрев консоль после нажатия на "протестировать"
*/
        url: require('./../api/assets/story.png'),
        filename: 'slash.png',
});

await this.$connect.send('VKWebAppDownloadFile', {
        url: 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
        filename: 'base.png',
});
```

**Comment by ilyapishchulin** [comment]
По относительному пути и не будет работать, base64 нужно поправить, спасибо

**Comment by daniluk4000** [comment]
> По относительному пути и не будет работать, base64 нужно поправить, спасибо

Это, конечно, можно пережить, но почему? В моем случае, чтобы запускать несколько окружений (альфа/бета/прод) мне придется пихать домен в переменные окружения или определять его адрес на фронтенде, но как будто бы это должно делаться на стороне ВК. 

Для меня это выглядит не сложно и логично. Не сложно, так как вы знаете полный путь, где запускается приложение, так как он прописан в его настройках, отдельно для каждой платформы (аппы/мвк/десктоп). В теории, вы можете просто определить абсолютный путь условной регуляркой, после чего подставить домен по виду `ДОМЕН_ИЗ_НАСТРОЕК`+`ОБРАТНЫЙ_СЛЕШ_ЕСЛИ_ЕГО_НЕТ`+`url_ОТ_ПОЛЬЗОВАТЕЛЯ`. 

Даже такой с виду замудренный вариант выглядит легче для реализации на вашей стороне, чем костыли от пользователей платформы.

**Comment by ilyapishchulin** [comment]
Увы, но так внутренне сделано на обеих платформах

**Comment by eolme** [comment]
@daniluk4000, без регулярок и костылей можно - пишется буквально в одну строчку:

```js
const file = new URL(url, `${location.origin}/${location.pathname}/`);
```

**Comment by daniluk4000** [comment]
@eolme, прошу прощения за откровенность, но я считаю, что если пользователю приходится делать дополнительные действия, которые могли быть на уровне платформы, каждый раз при вызове метода - это костыль. Регулярки я описывал как вариант для реализации на стороне ВК. 

В компании, где я работаю, много проектов на платформе. В некоторых из них есть загрузка файлов. Для того, чтобы реализовать загрузку файлов по типу "вызов одной функции", мне придется добавить нечто похожее на то, что вы описали выше, в нашу библиотеку для работы с ВК. 

А теперь представьте, что есть большой проект, в котором много загрузок файлов. Разработчикам также придется делать методы для загрузки, чтобы не дублировать код добавления урла к локальным файлам каждый раз при вызове метода. Я благодарен за workaround, но куда лучше было бы реализовать это на уровне платформы.

**Comment by eolme** [comment]
@daniluk4000, как количество проектов или их размер влияют на реализацию? Тем более, как вы говорите, у вас уже есть библиотека-обертка, и если вам так критично использовать релативные пути - я думаю не составит труда внести изменения.

Я не отрицаю то, что на платформе было бы неплохо это реализовать, я просто подметил, что можно сделать без регулярок, и вы переоцениваете сложность реализации со своей стороны.

**Comment by daniluk4000** [comment]
@ilyapishchulin новые симптомы

![изображение](https://user-images.githubusercontent.com/10450717/102343415-95326f00-3fab-11eb-9efe-baaeba6248cf.png)
![изображение](https://user-images.githubusercontent.com/10450717/102343420-96fc3280-3fab-11eb-9c9f-0f307bff6d88.png)

Приложение стало реагировать на загрузку base64 и файлов по абсолютным путям, но в случае с base64 крашится мини приложение, а в случае с абсолютным путём вообще всё приложение

**Comment by ilyapishchulin** [comment]
Сейчас как обстоят дела?

**Comment by nikolaytuz** [comment]
Здравствуйте. Пробовал этот метод, после сохранения, фото не появляется в галереи, в файловой системе написано 0 б. Прикладываю скрин. https://ibb.co/6PFF97R
Версия андроид 9
На айфоне отлично все работает.

**Comment by ilyapishchulin** [comment]
Нужен пример запросы

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
