### ISSUE TITLE
[Feature Request] указание лимита в VKWebAppGetFriends при использовании multi

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-bridge#177]
Очень хочется в VKWebAppGetFriends указывать минимальные максимальное количество друзей, которое можно выбрать (при условии, что multi: true). Это позволит работать с такой логикой, как, например, "пригласи от 2 до 4 друзей в свой сквад". 

При этом оба параметра не должны быть обязательными к заполнению. Можно передать как ни один из параметров, так и либо max, либо min, либо оба сразу.

**Comment by daniluk4000** [comment]
Пример реального использования такой логики, из-за которой не получится переехать на метод
![изображение](https://user-images.githubusercontent.com/10450717/91960868-1888c700-ed13-11ea-969b-20a37b825c27.png)

**Comment by Pronin-vk** [comment]
Спасибо за обращение, рассмотрели в команде платформы, пока не планируем реализовывать данный функционал.
