### ISSUE TITLE
Дополнительная проверка чтоб event.detail.data объект

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/vk-bridge#178]
Иногда в Sentry приходят сообщения об ошибке в vk-bridge

![image](https://user-images.githubusercontent.com/8437497/91968109-d49abf80-ed1c-11ea-80cf-4e4218a21e60.png)
![image](https://user-images.githubusercontent.com/8437497/91969155-5d662b00-ed1e-11ea-9e36-deff6f37ef6e.png)

Вероятно так происходит из-за браузерных расширений, которые шлют в postMessage всякие сообщения странные.

Воспроизвести можно на https://vk.com/covid19

Если в консоль вставить этот код
```js
$('.app_container iframe').contentWindow.postMessage({type:"123",data:"ACK"}, '*')
```
![image](https://user-images.githubusercontent.com/8437497/91971583-1c701580-ed22-11ea-9eee-17032128e8ef.png)

Проблема вот тут 
https://github.com/VKCOM/vk-bridge/blob/31d7c9890b3b676fc7e2705b069e91eae0af0622/src/promisifySend.ts#L98

поскольку сообщения может прислать кто угодно `event.detail.data` может оказаться и строкой и чем угодно, хотя ожидается объект.

**Comment by ilyapishchulin** [comment]
`document.getElementsByClassName('app_container app_container--vk-app')[0].children[0].contentWindow.postMessage({type:"123",data:"ACK"}, '*')`
