### ISSUE TITLE
На ПК не работает отправка параметров в Sandbox'e CallAPIMethod

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-bridge#180]
При попытке подставить params при отправке CallAPIMethod в [VK Bridge Sandbox](https://vk.com/app6909581#VktXZWJBcHBDYWxsQVBJTWV0aG9kQCU3QiUyMm1ldGhvZCUyMiUzQSUyMnVzZXJzLmdldCUyMiUyQyUyMnBhcmFtcyUyMiUzQSUyMiU3QiU3RCUyMiU3RA==) на ПК версии при попытке вставить через UI выдается ошибка.

![изображение](https://user-images.githubusercontent.com/10450717/92118890-b8bc1a00-edff-11ea-89c6-e95af77bff91.png)  
![изображение](https://user-images.githubusercontent.com/10450717/92127520-105f8300-ee0a-11ea-90c5-a38176c57041.png)

---

Workaround: подставить параметры в JSON лапками

![изображение](https://user-images.githubusercontent.com/10450717/92118974-d2f5f800-edff-11ea-9c7d-065dc7a6003b.png)

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
