### ISSUE TITLE
Реализация ошибки о неподдержке события

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#181]
Предлагаю реализовать выбрасывание ошибки о том, что событие не поддерживается в методе `send`.

Сейчас в таком случае просто promise не выполняется, потому что ничего не отсылается ([bridge.ts#L109](https://github.com/VKCOM/vk-bridge/blob/8961f2d0e0214f1a1a3ac703d6539929aa53ee50/src/bridge.ts#L109))

**Comment by ilyapishchulin** [comment]
Кажется, что все события желательно проверять через supports, уточню

**Comment by Pronin-vk** [comment]
В данный момент на платформе есть выброс исключения unsupported platform
