### ISSUE TITLE
Просьба дополнить метод status.get

### ISSUE THREAD

**Issue by seadinkin2002** [VKCOM/vk-bridge#183]
Добрый вечер! Я разработчик сервиса тексты песен vk.com/lyrics. Сейчас мы занимаемся оптимизацией сервиса, редактируем в дизайне. Одной из основных функций есть моментальное получение текста трека из статуса. Отправляется название песни на наше api, и только потом получается картинка. Если бы это можно было как-то сделать так, чтоб метод bridge.send("VKWebAppCallAPIMethod", {"method": "status.get".., возвращал ссылку на обложку, это бы уменьшило время ответа (сейчас мы ждем ответа от нашего api). 

Также есть просьба дать доступ к получения доступа к аудио https://vk.com/dev/vk_bridge_events_7?f=%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F . Сейчас очень мало возможностей реализовано из-за отсутствия данной возможности: делался бы поиск по трекам пользователя и базе вк, получение треков пользователя, недавно прослушанных. Благодаря этому сервис был бы более user friendly

**Comment by ilyapishchulin** [comment]
Секция audio закрыта, добавлять такой метод пока не планируем
