### ISSUE TITLE
Вызов VKWebAppShowNativeAds с отсутствием поддержки (к примеру на ПК) не шлёт Result\Failed

### ISSUE THREAD

**Issue by ub1x** [VKCOM/vk-bridge#187]
Вызывая VKWebAppShowNativeAds на десктопе не приходят события VKWebAppShowNativeAdsFailed\VKWebAppShowNativeAdsResult

Аналогично ничего не приходит в then и catch  при использовании bridge.send('VKWebAppShowNativeAds').then().catch()

**Comment by ilyapishchulin** [comment]
Нужно проверять поддерживается ли событие через bridge.supports
