### ISSUE TITLE
Добавление мини-приложения на главный экран устройства IOS

### ISSUE THREAD

**Issue by seadinkin2002** [VKCOM/vk-bridge#188]
Вызов события VKWebAppAddToHomeScreen позволяет добавить VK Mini Apps на экран устройства.
Платформы
Android

С недавнего времени в ios 14, появились иконки, так почему бы пользователям ios не дать данный функционал?

**Comment by ilyapishchulin** [comment]
Добавление шортката на главный экран в iOS невозможно
