### ISSUE TITLE
Перестает работать событие send

### ISSUE THREAD

**Issue by Stoope** [VKCOM/vk-bridge#191]
Платформа: web
Кейс:
Нужна возможность сделать звонок, реализовал внутри приложения через `target="_parent"`: 
```html
<a target="_parent" href="tel:+79998889988">link</a>
```
работает, после нажатие по ссылке происходит выбор приложения для звонка.
Проблема: после нажатия по ссылке (также происходит с `mailto`), перестает работать `bridge.send`, до момента нажатие он работает, после никак не реагирует: нет ошибок, нет модальных окон там где это нужно (вызываю `VKWebAppShowWallPostBox`).
Пробовал делать это вручную
```javascript
postMessage({
  handler: 'VKWebAppShowWallPostBox',
  params: {
    message:
      'test',
    request_id: 2,
  },
  type: 'vk-connect',
  connectVersion: '2.3.0',
});
```
поведение такое же (до клика работает, после нет)

**Comment by ilyapishchulin** [comment]
Подскажите, почему именно через "parent"?

**Comment by Stoope** [comment]
@ilyapishchulin в противном случае будет нарушение CSP `Refused to frame '' because it violates the following Content Security Policy directive: "default-src *". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by ilyapishchulin** [comment]
Получается ломаются промисы?

**Comment by Stoope** [comment]
Ломается метод `postMessage`, никаких ошибок или логов я при этом не вижу. Возможно ошибка где то на "принимающей" стороне а не на уровни этой библиотеки

**Comment by ilyapishchulin** [comment]
Не нужно использовать postMessage на прямую, следует подключить нашу библиотеку

**Comment by Stoope** [comment]
Да, я использую `bridge.send`, `postMessage` это я уже углубился в попытках найти причину. У `bridge.send` поведение аналогичное

**Comment by ilyapishchulin** [comment]
Не воспроизвелось с Safari версии 14.0.1 (16610.2.11.51.8)

**Comment by Stoope** [comment]
Хм, да, в safari работает, значит проблема в chrome
