### ISSUE TITLE
Несколько параллельных вызовов VKWebAppStorageSet ломают bridge.send

### ISSUE THREAD

**Issue by Reeywhaar** [VKCOM/vk-bridge#192]
**Дано:**
- vk-bridge v2.3.0
- Приложение запущено в приложении на ios (или на android)

**Кейс**
```js
import bridge from "@vkontakte/vk-bridge";

const set = (key) => bridge.send("VKWebAppStorageSet", { key, value: "test" }).then(() => {
  console.log("test")
});

Promise.all([
  set("a"),
  set("b"),
  set("c"),
]).then(() => {
  console.log("done")
}).catch(() => {
  console.log("error")
})
```

**Ожидание:**
В консоль выведется три раза "test", затем "done"

**Реальность:**
Выведется "test" один или два раза. Ни "done", ни "error" не будет выведено в консоль.

Несколько промисов никогда не разрезолвятся ни зареджектятся. Останутся висеть.

**Comment by ilyapishchulin** [comment]
Напишите в ишью, если актуально
