### ISSUE TITLE
[Feature Request] Метод генерации хеша

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/vk-bridge#193]
было бы круто неплохо добавить метод, который генерирует хеш на основе времени и секретного ключа.

К примеру сделать его склейкой секретного ключа + unixTime, а в ответ вернуть 
{ hash , unixTime } 

Так разработчики смогут себя довольно неплохо обезопасить от запросов "из вне", передавая вместе с запросами на сервер ещё и хеш.

**Comment by evtn** [comment]
Очень интересный issue, поддерживаю. Хотя это и не сможет обезопасить на 100%, но можно будет отсеять б**о**льшую часть умных злоупотребителей.

**Comment by antonzahariev** [comment]
ну видно что школьник придумывал но поддерживаю

**Comment by ItzNeviKat** [comment]
Очень интересный issue, поддерживаю. Хотя это и не сможет обезопасить на 100%, но можно будет отсеять большую часть умных злоупотребителей.

**Comment by AlexandrFiner** [comment]
Очень интересный issue, поддерживаю. Хотя это и не сможет обезопасить на 100%, но можно будет отсеять большую часть умных злоупотребителей.

**Comment by ilyapishchulin** [comment]
Добавили VKWebAppCreateHash, спасибо за ишью
