### ISSUE TITLE
[Bug] Многократный вызов любого метода, ведущий за собой открытие попаута от вк

### ISSUE THREAD

**Issue by ub1x** [VKCOM/vk-bridge#194]
Вызываем >1 раз любой метод, который требует разрешение юзера (к примеру VKWebAppAddToFavorites), и получаем дублирование этих самых окошек для разрешения.

**Comment by ub1x** [comment]
Похоже на поведение #142

**Comment by ilyapishchulin** [comment]
Будем разбираться с этой проблемой в рамках #142
