### ISSUE TITLE
[Bug] VKWebAppSendToClient не возвращает результат (m.vk.com, IOS)

### ISSUE THREAD

**Issue by nickname32** [VKCOM/vk-bridge#195]
В моём приложении https://vk.com/app7607943 происходит бак, который возникает из-за того, что не приходит ответ от VKWebAppSendToClient.
https://github.com/Sociorate/sociorate-vk-mini-app/blob/7a0d06d31140df6578b1effacce7b503957360c1/src/panels/Home.js#L501
На этом моменте код останавливается. Бесконечный await bridge.send("VKWebAppSendToClient").

**Comment by ilyapishchulin** [comment]
Поправим

**Comment by ilyapishchulin** [comment]
Исправлено, спасибо!
