### ISSUE TITLE
[Bug] Не поддерживается порядок возвращаемых событый (или просто нет более конкретных идентификаторов)

### ISSUE THREAD

**Issue by nickname32** [VKCOM/vk-bridge#196]
Конкретно встретился с проблемой, когда несколько асинхронных запросов await bridge.send('VKWebAppStorageGet', ... возвращали значения которые не запрашивали (но которые запрашивали другие в это же время).

**Comment by ilyapishchulin** [comment]
Нужно поподробнее, речь про Promise?

**Comment by nickname32** [comment]
> Нужно поподробнее, речь про Promise?

Отправляетсяя событие
В это-же время (асинхронно) отправляется это событие ещё раз

Два запроса по одному событию, но с разными пэйлоадами ожидают возврата результата

Возвращается ответ на второе (асинхронно) отправленное событие, но оно принимается там, где было отправленно первое.
Возвращается ответ на первое отправленное событие, но оно принимается там, где было отправлено второе.

Это происходит, как я понимаю, из-за того, что при отправке одного и того же события, ответ возвращается под одним и тем-же кодом события, так что если они возвращаются не в нужном порядке, хэндлы могут поймать ответ не на свои запросы.

**Comment by wolframdeus** [comment]
@nickname32 вряд ли, потому что когда вы вызываете метод, ему присваивается request_id, вам возвращает промис ожидающий выполнения конкретно этого request_id (это можно установить по исходникам).

Есть какой-то пример кода в котором такая проблема воспроизводима?

**Comment by nickname32** [comment]
> @nickname32 вряд ли, потому что когда вы вызываете метод, ему присваивается request_id, вам возвращается промис ожидающий выполнения конкретно этого request_id (это можно установить по исходникам).
> 
> Есть какой-то пример кода в котором такая проблема воспроизводима?

Просто сделайте несколько асинхронных запросов для получения данных из storage, проблема должна возникнуть.

**Comment by ilyapishchulin** [comment]
А если попробовать подставлять request_id?

**Comment by ilyapishchulin** [comment]
Нет обратной связи
