### ISSUE TITLE
[Bug] VKWebAppLocationChanged не приходит когда меняется locaiton непосредственно в адресной строке

### ISSUE THREAD

**Issue by nickname76** [VKCOM/vk-bridge#197]
Похоже, что VKWebAppLocationChanged присылается только после вызова VKWebAppSetLocation, а, должен, думаю, присылаться и когда locaiton изменён непосредственно пользователем в адресной строке.
Браузер - firefox, клиент vk.com.

**Comment by ilyapishchulin** [comment]
Добавили VKWebAppChangeFragment, как на мобильных устройствах

**Comment by nickname76** [comment]
Я думаю это должно присылаться ещё и при запуске приложения

**Comment by ilyapishchulin** [comment]
При запуске приложения хеш доступен в window.locatiln.hash, событие нацелено только на смену хеша.
