### ISSUE TITLE
Повторные показы окна с запросом доступов при использовании VKWebAppGetAuthToken

### ISSUE THREAD

**Issue by soofft91** [VKCOM/vk-bridge#198]
Подскажите пожалуйста, что не так я делаю😰
Перед тем как обратится к методу api для которого нужны специальные разрешения я получаю токен пользователя с соответствующими правами.
```
const { access_token } = await bridge.send("VKWebAppGetAuthToken", {
	app_id: 1111111,
	scope: "groups",
});
```
Полученный токен использую в запросе к api и все прекрасно работает. Теперь стоит гдето в другом месте запросить токен уже с другими правами, например так:
```
const { access_token } = await bridge.send("VKWebAppGetAuthToken", {
	app_id: 1111111,
	scope: "stats",
});
```
То вернувнись обратно на страницу где запрашивал первый токен с правами  "groups", снова появится окно с запросом доступа к  "groups". Приложение будто не запоминает какие разрешения уже дал пользователь.

**Comment by ilyapishchulin** [comment]
подскажешь платформу?

**Comment by soofft91** [comment]
> подскажешь платформу?

VK Mini Apps

**Comment by soofft91** [comment]
Вообще везде где проверял работает одинаково.

iPhone 5s/ iOS 11.2.1: открывал через приложение VK
macOS 10.14.6: safari 12.1.2, chrom 87.0.4280.88 (Официальная сборка), (x86_64)
windows 10: chrome 87.0.4280.88 (64 бит), Edge 44.177763.831.0

Я почти уверен что я как-то не правильно понял схему работы с токенами пользователя. Я запрашиваю токен с определенными правами только на той "странице" на которой есть функционал требующий этих прав. То есть стараюсь действовать по рекомендациям ВК, запрашивать права по мере необходимости. 

Приложение в ВК: https://vk.com/app7686860
Код где есть получение токена: 1) https://github.com/soofft91/smm-helper/blob/main/src/panels/WatchStats.jsx#L29
2) https://github.com/soofft91/smm-helper/blob/main/src/panels/SelectGroup.jsx#L20

**Comment by ilyapishchulin** [comment]
Спасибо, посмотрим

**Comment by ilyapishchulin** [comment]
Сделали, спасибо
