### ISSUE TITLE
VKWebAppShowNativeAds ничего не возвращает в случае закрытия рекламы

### ISSUE THREAD

**Issue by vforsh** [VKCOM/vk-bridge#201]
Здравствуйте,

Вопрос относительно работы метода [VKWebAppShowNativeAds](https://vk.com/dev/vk_bridge_methods?f=3.5%20VKWebAppShowNativeAds)

Я работаю с Direct Games, поэтому вызов метода происходит через vkBridge:
`bridge.send("VKWebAppShowNativeAds", { ad_format: "reward" })`

Иногда при вызове этого метода с параметром `ad_format: "reward"` появляется реклама с кнопкой Close в левом верхнем углу. При нажатии на эту кнопку реклама просто закрывается, но метод VKWebAppShowNativeAds ничего не возвращает, не происходит ни resolve, ни reject промиса.

Мне кажется это баг, и в случае закрытия метод должен что-то возвращать, чтобы игра могла отреагировать соответсвующе. Например, сообщить пользователю - "Досмотрите видео до конца, чтобы получить награду (монеты и т.п.)"

![2020-12-24_10-43-46](https://user-images.githubusercontent.com/190223/103071636-0f2ead80-45d5-11eb-9b82-8448ef440cf2.png)

**Comment by ilyapishchulin** [comment]
Укажите платформу, пожалуйста
Android/iOS?

**Comment by maklakovss** [comment]
у меня подобное проявляется на Андроиде

**Comment by vforsh** [comment]
@ilyapishchulin Такое точно происходит на iOS. Насчёт андроид не знаю, так как устройств для тестирования у меня нет.

**Comment by maklakovss** [comment]
@ilyapishchulin есть движения по данному вопросу?

**Comment by ilyapishchulin** [comment]
Да, скоро исправим

**Comment by maklakovss** [comment]
> Да, скоро исправим

а можно уточнить по срокам? достаточно критичная вещь @ilyapishchulin

**Comment by ilyapishchulin** [comment]
Android скоро

**Comment by maklakovss** [comment]
> Android скоро

еще не готово? @ilyapishchulin

**Comment by ilyapishchulin** [comment]
Android фикс в продакшене

**Comment by maklakovss** [comment]
@ilyapishchulin а по ios в процессе? когда ожидать?

**Comment by ilyapishchulin** [comment]
Пока нет сроков

**Comment by AlexandrFiner** [comment]
Встречал подобное. Решил костылями. Перед самым вызовом рекламы вывожу сообщение, что рекламу нужно досмотреть, если реклама досмотрена, то убираю. Как решение - вполне

**Comment by AlexandrFiner** [comment]
Причем иногда идет возврат БЕЗ рекламы, причем успешный.

**Comment by SkyGopnik** [comment]
Похоже решения не дождетесь) На момент написания прилы в ноябре, баг был.

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Нужно больше подробностей, сейчас баг актуален?
Если да, то нужны примерные шаги воспроизведения, описание девайса, версии OS и т.д.

**Comment by GlukhovaJulia** [comment]
Проблема еще актуальна. На ios у меня никогда не происходит ни then, ни catch, сколько бы по времени игрок не смотрел на рекламу.

bridge.send("VKWebAppShowNativeAds", { ad_format: "reward" }).then((data): boolean =>
		{
			return data.result;
		}).catch((err: any): boolean =>
		{
			return false;
		});

**Comment by GlukhovaJulia** [comment]
На ios до сих пор не срабатывает ни then, ни catch. При этом реклама показывается.

bridge.send("VKWebAppShowNativeAds", { ad_format: "reward" }).then((data): void =>
{
....
}).catch((error): void =>
{
....
});

**Comment by x10der** [comment]
У нас такое поведение с методом VKWebAppCheckNativeAds на Android. Первый вызов возвращает ответ как и описано в доке: {"result":false} (при отсутствии доступной рекламы). Но если еще раз вызвать этот метод, промис уже не резолвится, а так и висит.

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
