### ISSUE TITLE
[Feature Request] Проверить добавлена ли игра в избранное

### ISSUE THREAD

**Issue by vforsh** [VKCOM/vk-bridge#202]
В документации описана механика добавления игры в избранное (левой меню в десктопной версии ВК) - https://vk.com/dev/game_menu

Однако метода для проверки, добавлена ли игра в избранное, нет. С точки зрения UX было бы правильно скрывать кнопку если игра уже есть в избранном.

Подобное реализовано в методах `VKWebAppGameInstalled` и `VKWebAppAddToHomeScreenInfo`

**Comment by ilyapishchulin** [comment]
Спасибо, подумаем

**Comment by ilyapishchulin** [comment]
Сделали query параметр, спасибо за ишью
