### ISSUE TITLE
Добавить в VKWebAppGetGeodata параметр для запрета кэширования местоположения

### ISSUE THREAD

**Issue by vkproger** [VKCOM/vk-bridge#203]
Дело в том, что метод VKWebAppGetGeodata возвращает верные координаты при первом запросе, но при последующих запросах возвращает эту же позицию из кэша, поэтому местоположение пользователей отображается некорректно, а обновляется она только в течение 5-10 минут.

Было бы неплохо добавить в параметры метода VKWebAppGetGeodata свойство maximumAge для запрета кэширования, либо просто для установки времени кэширования, как в стандартном  Geolocation API, чтобы получить точные обновленные координаты.

**Comment by ilyapishchulin** [comment]
О какой платформе речь? iOS/Android/Web/Mobile Web?

**Comment by vkproger** [comment]
> О какой платформе речь? iOS/Android/Web/Mobile Web?

Забыл добавить. Проверял с Android клиента, даже с нескольких. Везде после первого вызова далее возвращает старые координаты. Тоже самое и в m.vk.com. Но там можно использовать и navigator.geolocation, запретив при этом кэширование.

Также с клиента android не работает обычный запрос через navigator.geolocation, хотя на ios все работает.

**Comment by ilyapishchulin** [comment]
Кешируется на стороне Google сервисов

**Comment by vkproger** [comment]
Странно, конечно, что Google сервисы кешируют их только в ВК, ибо в других приложениях на андроиде я такого не наблюдал. В любом случае, даже если и есть в них кеширование, то можно запретить их или установить для них лимит. Вам виднее, конечно, что там да как

**Comment by eolme** [comment]
@ilyapishchulin, не понял о чём ты. Google сервисы же отдают местоположение только если выключено местоположение на устройстве.

Как я понимаю, тут проблема, что со ВКЛЮЧЕННОЙ геолокацией кэшируется. В таком случае определённо со стороны нативного клиента проблема, переоткрыть бы.

**Comment by ilyapishchulin** [comment]
Я уточнил у наших мобильных разработчиков, мы ничего не сохраняем на своей стороне, каждый раз запрашиваем

**Comment by eolme** [comment]
Вот сейчас открыл доку, там есть параметры с какой периодичностью и приоритетом запрашивать

**Comment by vkproger** [comment]
> Я уточнил у наших мобильных разработчиков, мы ничего не сохраняем на своей стороне, каждый раз запрашиваем

Да, такое есть даже на вебе, по умолчанию при запросе местоположение отдают из кеша (после повторного запроса). Но если передавать при этом дополнительные параметры, то возвращает обновленные координаты. Может и там есть нечто подобное

**Comment by KuVaUgU** [comment]
@vkproger а подскажи пожалуйста модель своего девайса и версию ОС. Определение геопозиции запрашивается каждый раз заново с PRIORITY_HIGH_ACCURACY, поэтому пока непонятно в чём может быть проблема. Подозреваю девайс специфик проблему.

**Comment by vkproger** [comment]
@KuVaUgU Samsung Galaxy J8, Andoid 8.0 . Но проблема не только у меня, но и у многих пользователей моего сервиса (к слову, через VK Bridge Sandbox тоже самое). Могу запросить девайсы и у пользоваталей, при необходимости
