### ISSUE TITLE
Мобильное приложение. VKWebAppShowWallPostBox не добавляет в attachments ссылку на внешний ресурс

### ISSUE THREAD

**Issue by avetall87** [VKCOM/vk-bridge#205]
При публикации поста через vk-bridge из мобильного приложение в attachments не добавляется ссылка на внешний ресурс.

При вызове метода vk-bridge появляется диалог в котором есть только сообщение, а ссылки нету.

В песочнице воспроизводится аналогичное поведение (так же из мобильного приложения):
https://vk.com/app6909581#VktXZWJBcHBTaG93V2FsbFBvc3RCb3hAeyJtZXNzYWdlIjogIkhlbGxvISJ9

***Пример вызова***:
bridge.send("VKWebAppShowWallPostBox", {
            "attachments": [
                link
            ],
            "message": `${postMessage}`
        })
        .then(response => { ... });
        .catch(exception => { ... });

**Comment by ilyapishchulin** [comment]
Спасибо за ишью, обновили документацию

https://vk.com/dev/vk_bridge_events_2?f=Публикация%20записей%20на%20стене
