### ISSUE TITLE
Из webview открывается неправильная ссылка

### ISSUE THREAD

**Issue by vforsh** [VKCOM/vk-bridge#206]
В игре есть ссылка, которая ведёт на приложения сообщества
`<a target="_blank" href="https://vk.com/apps?act=apps&gid=201363314">Игры RoboWhale</a>`

Если игра запущена с десктопного vk.com или m.vk.com, то ссылка перекидывает на указанную страницу. Если же игра запущена из webview (каталог Direct Games), то по клику перекидывает в каталог VK Mini Apps
![IMG_1159](https://user-images.githubusercontent.com/190223/105480638-0d7d0600-5cb7-11eb-9da8-93374ad606ef.png)

Странно то, что ссылки на сообщество (https://vk.com/robowhale) или на топик в сообществе (https://vk.com/topic-201363314_46696414), работают нормально, а вот с приложениями сообщества проблема.

**Comment by kuhel** [comment]
Приложения сообществ не работают на мобильных клиентах и это deprecated платформа, которая в скором времени перестанет существовать
