### ISSUE TITLE
Отсутствуют типы для методов  рекламой

### ISSUE THREAD

**Issue by nikitakoschelenko** [VKCOM/vk-bridge#207]
Если попытаться вызвать метод `VKWebAppShowNativeAds`, то Typescript выдаёт ошибку – метода нет в списке.
![AvukmlUqR_w.jpg](https://user-images.githubusercontent.com/24193020/105607736-a2fcc080-5db1-11eb-86f6-49e4ef0a1fbe.jpg)

**Comment by otopba** [comment]
Ждемс

**Comment by anzolo** [comment]
Подтверждаю, ждёмс
