### ISSUE TITLE
Не отслеживается событие VKWebAppShowStoryBoxLoadFinish

### ISSUE THREAD

**Issue by FragDealer** [VKCOM/vk-bridge#211]
После публикации истории методом **VKWebAppShowStoryBox**, не всплывает событие **VKWebAppShowStoryBoxLoadFinish** в обработчике  **vkBridge.subscribe** на Android и iOS.

```
vkBridge.send('VKWebAppInit');
vkBridge.subscribe(e => {
	alert(e.detail.type + ':   ' + JSON.stringify(e.detail.data));
});
vkBridge.send('VKWebAppShowStoryBox', {...});
```

После публикации истории всплывает только событие **VKWebAppShowStoryBoxResult**, а **VKWebAppShowStoryBoxLoadFinish** не отслеживается.

**Comment by ilyapishchulin** [comment]
Спасибо, посмотрим

**Comment by FragDealer** [comment]
Ещё дополню идеей/предложением, при реализации метода VKWebAppShowStoryBox через примисы в .then всплывает событие VKWebAppShowStoryBoxResult, а доступ к событию VKWebAppShowStoryBoxLoadFinish не реализован:
```
vkBridge
    .send('VKWebAppShowStoryBox', {...})
    .then(data => {
        // -> VKWebAppShowStoryBoxResult
    });
```

**Что если возвращать дополнительный промис, например:**
```
vkBridge
    .send('VKWebAppShowStoryBox', {...})
    .then(data => {
        // -> VKWebAppShowStoryBoxResult
        data.onLoadFinish.then(data1 => {
             // -> VKWebAppShowStoryBoxLoadFinish 
        });
    });
```

**вот какую логику я имею ввиду:**
```
function TEST(){}

TEST.send = function() {
    let VKWebAppShowStoryBoxResult = new Promise((resolve, reject) => {
	
        let VKWebAppShowStoryBoxLoadFinish = new Promise((resolve_1, reject_1) => {
            setTimeout(() => resolve_1({event: 'VKWebAppShowStoryBoxLoadFinish'}), 5000);
        });
		
        let data = {event: 'VKWebAppShowStoryBoxResult', onLoadFinish: VKWebAppShowStoryBoxLoadFinish};
        setTimeout(() => resolve(data), 1000);

    });
    return VKWebAppShowStoryBoxResult;
}

TEST
    .send()
    .then(data => { 
        console.log(data.event);
        data.onLoadFinish.then(data_1 => {
            console.log(data_1.event);
        });
    });
```

**Comment by ilyapishchulin** [comment]
такую логику пока, увы, дать не можем

после публикации поле должно начать возвращаться

**Comment by FunNikita** [comment]
Каким образом можно отправить видео? Ибо в нём содержатся номера телефонов.

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
