### ISSUE TITLE
[BUG] VKWebAppSetLocation дублирует историю

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#213]
На платформе VKCOM вызов `VKWebAppSetLocation` дублирует историю:

![WaC6tX2uLK0](https://user-images.githubusercontent.com/11076888/106797768-7df03380-6676-11eb-8413-4302e25a54e3.jpg)

**Comment by ilyapishchulin** [comment]
Спасибо, посмотрим

**Comment by ilyapishchulin** [comment]
Попробуйте отправить параметр в params replace_state: true, это решит вашу проблему?

**Comment by eolme** [comment]
Да, спасибо, добавить в доку бы еще

**Comment by ilyapishchulin** [comment]
Done
