### ISSUE TITLE
VKWebAppShowNativeAds резолвится при выключенном интернете

### ISSUE THREAD

**Issue by vforsh** [VKCOM/vk-bridge#214]
Платформа iOS - включаем авиарежим, отключаем wifi. Запускаем rewarded ads `vkBridge.send("VKWebAppShowNativeAds", { ad_format: "reward" })` и этот промис резолвится. Правда резолвится он с результатом `{ no_ad_reason: false }`. Но тем не менее это же неправильно, ожидаемое поведение 
> нет интеренета => нет рекламы => reject

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Если актуально, то переоткройте ишью
