### ISSUE TITLE
Ошибка вызова VKWebAppShowOrderBox Iphone

### ISSUE THREAD

**Issue by M-Ulyanov** [VKCOM/vk-bridge#215]
Привет! При попытке открыть окно покупки через VKWebAppShowOrderBox на Iphone 11 pro , получаю ошибку Unsupported platform. В описании метода нет никаких ограничений по этому поводу. Как реализовать платежи на iphone? 
На андройде все работает нормально.

**Comment by kuhel** [comment]
Привет, доку поправим, в iOS метод не поддерживается, так как противоречит гайдлайнам AppStore
