### ISSUE TITLE
Метод VKWebAppAllowMessagesFromGroup отдает ошибку 

### ISSUE THREAD

**Issue by stis91** [VKCOM/vk-bridge#222]
Метод 
VKWebAppAllowMessagesFromGroup

Мой код: 

` bridge.send("VKWebAppAllowMessagesFromGroup", {
					"group_id": 203684352,
					"key": "dBuBKe1kFcdemzB"
				  }).then(data => {
					  console.log(data)
				  }).catch(err => {
					  console.log('Ошибка ', err)
				  })`

Событие повесил на клик по кнопке, все ок, всплывает модалка. Жмем разрешить и ловим ошибку: 

`Uncaught (in promise) TypeError: Cannot set property 'request_id' of undefined
    at ae.errorHandler (apps.ea6b226a2f9c461ebaab.js?55f7398a8dc2fb7d0d4f391ae470d79e:1)
    at onDone (apps.ea6b226a2f9c461ebaab.js?55f7398a8dc2fb7d0d4f391ae470d79e:1)
    at common.5dcee074e91a205348b9.js?7a0c536edf22c144f693:1
    at C.processResponse (common.5dcee074e91a205348b9.js?7a0c536edf22c144f693:1)
    at common.5dcee074e91a205348b9.js?7a0c536edf22c144f693:1
    at common_web.c364383dbcfa74510a2c.js?db600cf766a5734ea44baaf134b0154e:1`

При этом если id сообщества указать = 1 (group_id:1) - то консоль вернет объект, содержащий значение true - т.е. все ок. 
Также если отказать в разрешении все отрабатывает согласно документации. 
Но вот именно с моего тест сообщества мне не удается получить разрешение. 

Прошу помочь

**Comment by ilyapishchulin** [comment]
Не удалось воспроизвести, какие-то особые условия? Последняя версия пакета?

**Comment by ilyapishchulin** [comment]
Пока закрываю, нет подробностей
