### ISSUE TITLE
VKWebAppGetGeodata возвращает неверные координаты

### ISSUE THREAD

**Issue by vkproger** [VKCOM/vk-bridge#223]
VKWebAppGetGeodata возвращает всегда одни и те же координаты. Хоть ты переехал уже в другой город, но координаты все равно старые. Проблема особенно актуальна в клиентах на Android. За время существования моего мини приложения, на эту проблему пожаловались уже несколько тысяч android пользователей. Я рекомендую им использовать браузерную версию ВК для входа в мини апп, т.к. мы через веб версию используем Geolocation API на JS И там всё ок. Если проблему решить нельзя, то хотя бы добавьте поддержку данной API в клиент ВК на адроиде. На IOS она уже поддерживается.

Также ранее было сказано, что проблема в сервисах Google, а не в самом ВКонтакте. Тогда почему таких проблем нет у других приложений? Везде всё отлично работает, только на этой платформе есть с этим проблемы.

Если на фоне каждый раз открывать какую-либо карту, то геоданные обновляются и в ВК. Также они обновляются, если поменять геоданные через фейк GPS. 

Иногда местоположение неверное даже при первом запросе, но в основном проблема заключается в том, что всегда возвращаются одни те же координаты из кэша. Как вариант, если возможно, можно было бы добавить поддержку запроса местоположения через api на js.

Открыл новый ишью, т.к. проблема не решена уже почти 4 месяца.

**Comment by ilyapishchulin** [comment]
Нужен стабильный кейс для воспроизведения. Примеры устройств и побольше конкретики

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
