### ISSUE TITLE
Метод VKWebAppShowLeaderBoardBox не работает

### ISSUE THREAD

**Issue by zugzug90** [VKCOM/vk-bridge#224]
Вызов Метода `VKWebAppShowLeaderBoardBox` не делает ничего в браузере (десктоп), в _JS_-консоли никаких ошибок при вызове нет, в Network Tab новых вызовов тоже никаких.

Код вызова такой:
```
vkBridge.send("VKWebAppShowLeaderboardBox", {"params": {"user_result": 13, "global": 0}}).then(data => console.log(data.success)).catch(error => console.log(error));
```

Код вызывается после того, как метод `VKWebAppInit` уже точно отработал.

_Примечение:_ Само тестируемое приложение пока находится на стадии неопубликованного, но выставлено в настройках в Состояние "Приложение включено и видно всем"

**Comment by zugzug90** [comment]
Ping

**Comment by zugzug90** [comment]
Bump

**Comment by ilyapishchulin** [comment]
Возвращается ошибка о том, что метод не поддержан на платформе
Если актуально, попробуй воспроизвести в vk.com/sandbox_app

**Comment by zugzug90** [comment]
@ilyapishchulin  - Здравствуйте. Где и как я могу увидеть подобную ошибку?, в моей игре JS консоль пуста и Network вызовов нету никаких. 

Каким актуальным методом из VK Bridge / другой либы мне нужно пользоваться в таком случае? Я хочу выводить диалог очков игроков на мобильной версии и на десктоп. Но хотя бы на мобильной версии.

> Если актуально, попробуй воспроизвести в vk.com/sandbox_app

Открыл приложение на смартфоне (Android) - там нету данной или хотя бы похожей опции в меню методов вообще - `VKWebAppShowLeaderBoardBox`

**Comment by ilyapishchulin** [comment]
Попробуй тут vk.com/test_vkapp

**Comment by zugzug90** [comment]
@ilyapishchulin  - Видео прикрепил. Не нашёл какого-то релевантного метода под мои нужды. 

https://user-images.githubusercontent.com/2551174/120446106-eedbf980-c391-11eb-8061-2a31be3454fe.mp4

**Comment by ilyapishchulin** [comment]
Сверху введи свои кастомные параметры

**Comment by zugzug90** [comment]
@ilyapishchulin - Попробовал:

```
VKWebAppShowLeaderBoardBox
{"user_result": 1, "global": 0}
```

Ответ:

```
{"error_type":"client_error","error_data":{"error_code":1,"error_reason":"Unsupported platform"}}
```

![image](https://user-images.githubusercontent.com/2551174/120525966-608f6400-c3e1-11eb-80b2-923be1bff2ac.png)

Browser: Firefox, OS: Kubuntu 20.04

А что тогда делать? Какой правильный метод для показа диалога очков для игры ВК ?

**Comment by andrievskiy** [comment]
Добрый день. Метод VKWebAppShowLeaderBoardBox на данный момент поддерживается только для мобильных платформ. Если вам необходимо использовать лидерборд в web версии игры, то вы можете использовать https://vk.com/dev/apps.getLeaderboard для получения данных, а ui составляющую сделать на своей стороне.

**Comment by zugzug90** [comment]
@andrievskiy  - Здравствуйте. Дело в том, что он как раз и не работает у меня на мобильном устройстве. Подскажите, как правильно вызывать этот метод, можно ли где-то найти рабочий пример приложения с исходным кодом?

**Comment by zugzug90** [comment]
@ilyapishchulin  - Здравствуйте. Почему данный тикет был закрыт?

**Comment by ilyapishchulin** [comment]
> Вызов Метода VKWebAppShowLeaderBoardBox не делает ничего в браузере (десктоп)

Изначально говорилось о другой проблеме. Теперь перекинулись на мобильные устройства

**Comment by zugzug90** [comment]
@ilyapishchulin  - Нужно ли мне пересоздать баг с уточнением про мобильную версию?

/cc @andrievskiy

**Comment by ilyapishchulin** [comment]
Нет, можно описать подробнее проблему тут

**Comment by ilyapishchulin** [comment]
Если проблема актуальна, то переоткройте ишью
