### ISSUE TITLE
[Feature] Энергосбережение

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#225]
На iOS при энергосбережении все анимации идут прерывисто, хотелось бы как нибудь узнавать, что включено энергосбережение.

Safari (WebView) напрямую не предоставляет API для получения заряда батареи и состояния, включено ли энергосбережение.

Со стороны нативного клиента есть возможность дергать через isLowPowerModeEnabled.

**Comment by ilyapishchulin** [comment]
Подумаем, спасибо

**Comment by ilyapishchulin** [comment]
К удивлению и сожалению эта информация считается персональными данными и мы не можем ее отдавать

**Comment by eolme** [comment]
Я даже не знаю как на это реагировать

**Comment by eolme** [comment]
Забавно получается, что на Android, внезапно, это не считается персональными данными
