### ISSUE TITLE
[Bug] VKWebAppCallAPIMethod в постоянном состоянии pending при восстановлении из кэша

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#227]
Если вызвать VKWebAppCallAPIMethod и скрыть миниапп до ответа, то Promise остается в состоянии pending.

В нативном клиенте происходит следующие:

<img src="https://user-images.githubusercontent.com/11076888/117116347-4d1bb980-ad9f-11eb-9b1f-092513424524.png" width="800">

Соответственно, запросы закрываются, но до миниаппов не доходит информация о этом. Предлагаю либо не останавливать запрос, либо прокидывать ошибку с соответствующей информацией о том, что запрос был прерван.

**Comment by eolme** [comment]
Если кто-то столкнулся с такой же проблемой - легче всего перейти на jsonp.

**Comment by ilyapishchulin** [comment]
Спасибо, поправим

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
