### ISSUE TITLE
[Bug][Crit] VKWebAppAllowMessagesFromGroup не работает на mvk

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#232]
При нажатии на "Разрешить" не приходит никакого события, но при "Запретить" приходит `VKWebAppAllowMessagesFromGroupFailed`

**Comment by ilyapishchulin** [comment]
Не воспроизвелось, какая-то конкретная группа?

**Comment by eolme** [comment]
Вроде починили
