### ISSUE TITLE
Типизация bridge.supports

### ISSUE THREAD

**Issue by land47** [VKCOM/vk-bridge#233]
Нет подсказок по уже существующим методам в IDE

**Comment by ilyapishchulin** [comment]
Что именно нету? (e: VKBridgeEvent<AnyReceiveMethodName>), выдает подсказки

**Comment by land47** [comment]
В смысле
Не типизирован метод supports

**Comment by ilyapishchulin** [comment]
Прошу прощения, не так прочитал, типизируем

**Comment by ilyapishchulin** [comment]
Сделано, спасибо
