### ISSUE TITLE
При изменении navigation_bar_color все приложение моргает черным/белым

### ISSUE THREAD

**Issue by GMELUM** [VKCOM/vk-bridge#238]
[](url)В сервисе обнаружена проблема со сменой темы, нав и статус бара.
Без изменения navigation_bar_color все работает нормально. Но стоит добавить его изменение и очень сильно режет глаз.

Пример изменения темы из кода сервиса : 

```js
        switch (scheme) {
            case "space_gray": statusBarStyle = "light"; actionBarColor = "#19191a"; break;
            case "client_light": statusBarStyle = "dark"; actionBarColor = "#ffff"; break;
            case "blue_scheme": statusBarStyle = "light"; actionBarColor = "#141d24"; break;
            case "dark_scheme": statusBarStyle = "light"; actionBarColor = "#1a1b1d"; break;
            case "light_purple_scheme": statusBarStyle = "dark"; actionBarColor = "#ffff"; break;
            case "purple_scheme": statusBarStyle = "light"; actionBarColor = "#0d0d0d"; break;
        }

        if (bridge.supports('VKWebAppSetViewSettings')) {
            bridge.send('VKWebAppSetViewSettings', {
                'status_bar_style': statusBarStyle,
                'action_bar_color': actionBarColor,
                'navigation_bar_color': actionBarColor
            });
        }
```

[Демонстрация проблемы](https://vk.com/doc541919523_605898562) (включено изменение navigation_bar_color)
[Демонстрация нормального поведения](https://vk.com/doc541919523_605898827)  (в коде убрал navigation_bar_color)

[Сам сервис](https://vk.com/app7798122)

**Comment by GMELUM** [comment]
В сервисе отключил изменение цвета navigation_bar_color. С ним сервисом пользоваться не комфортно

**Comment by ilyapishchulin** [comment]
Посмотрим, спасибо

**Comment by ilyapishchulin** [comment]
Исправили, спасибо за ишью
