### ISSUE TITLE
Не работает метод VKWebAppCheckNativeAds

### ISSUE THREAD

**Issue by ComradeRevo** [VKCOM/vk-bridge#243]
Не работает метод VKWebAppCheckNativeAds. Начиная с 20.06.2021 данный метод перестал работать. Результат всегда result = false. При проверке передаю параметр ad_format = 'reward'. Использую для проверки, если реклама доступна, то вывожу кнопку в интерфейсе. Теперь рекламу за вознаграждение никто не смотрит (кнопка не выводится). При этом метод VKWebAppShowNativeAds рекламу за вознаграждение вроде как выводит. Но без проверки реклама может быть недоступна и пользователь получит непритный опыт - нажал кнопку, хотел получить дополнительные монеты, но реклама недоступна.

**Comment by ilyapishchulin** [comment]
Добрый вечер, укажите платформу, пожалуйста

**Comment by putyavka** [comment]
У меня на Андроиде промис вообще никогда не завершается, как будто метод отсутствует
const data = await vkBridge.send('VkWebAppCheckNativeAds', { ad_format: 'reward'});
так тоже не работает
const data = await vkBridge.sendPromise('VkWebAppCheckNativeAds', { ad_format: 'reward'});
Установлена последняя версия ВК приложения

**Comment by ComradeRevo** [comment]
> Добрый вечер, укажите платформу, пожалуйста

Здравствуйте! Платформа Android, HTML5. Сейчас проверка иногда возвращает true. Но при этом метод VKWebAppShowNativeAds работает (показывает рекламу), даже, если проверка VKWebAppCheckNativeAds вернула false. Эти оба метода связаны между собой или нет?

**Comment by putyavka** [comment]
Проверил
`vkBridge.supports('VkWebAppCheckNativeAds')`
не возвращает **true** ни на iOS, ни на Android

**Comment by ilyapishchulin** [comment]
@putyavka vkBridge.supports('VKWebAppCheckNativeAds')

**Comment by ilyapishchulin** [comment]
Как сейчас обстоят дела?

**Comment by ilyapishchulin** [comment]
Видимо, не актуально
