### ISSUE TITLE
Добавить метод получения window.parent.innerHeight/innerWindth

### ISSUE THREAD

**Issue by GMELUM** [VKCOM/vk-bridge#245]
Эти параметры были бы очень полезны на Desktop и помогут сделать использование сервисов гораздо комфортнее.

сейчас для получения innerHeight приходится деплать так:
*Не очень стабильно + может быть неточность из за отсутствия поддержки availTop на некоторых браузерах.
```js
const innerHeight = window.outerHeight - ((window.screen as any).availTop || 150);
```

Хотелось бы иметь метод ч помощью которого можно получить innerHeight так:

```js
bridge.send("GetScreenVKSize").then((data) => {
    const innerHeight = data.innerHeight;
    const innerWidth = data.innerWidth;
})
```

Для чего метод? Для изменения размера фрейма адаптируясь на размер размера всего браузера.
Писал предложения добавить это со стороны ВК год назад почти... тишина... Может тут поймут что это полезная возможность. Спасибо за внимание!

**Comment by eolme** [comment]
В VKWebAppUpdateConfig приходят viewport_width и viewport_height

**Comment by GMELUM** [comment]
Да, действительно, спасибо! =)
