### ISSUE TITLE
Не срабатывают события ответа на VKWebAppGetAuthToken

### ISSUE THREAD

**Issue by GMELUM** [VKCOM/vk-bridge#246]
Не срабатывают события на Android:
VKWebAppAccessTokenFailed

На vkcom/mvk срабатывают. IOS не проверял.
Приходится обходным путем отлавливать ошибку:

```js
        bridge.send("VKWebAppGetAuthToken", { "app_id": 1, "scope": "stories,groups" })
        .then((data) => {***})
        .catch(() => {***})
```

по доке должно работать так:

```js
         switch (e.detail.type) {
                 case "VKWebAppAccessTokenFailed": ***; break;
                 case "VKWebAppAccessTokenReceived": ***; break;
         }
```

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
