### ISSUE TITLE
VkWebAppShowNativeAds web bug

### ISSUE THREAD

**Issue by ub1x** [VKCOM/vk-bridge#249]
Странное поведение с веба, если нажать "пропустить" при просмотре прелоадера через 10 секунд — придет ошибка.

А если ничего не жать, то буквально через 3 секунды реклама сама закроется и придет уже result: true, какой смысл в кнопке через 10 секунд тогда?)
![image](https://user-images.githubusercontent.com/45757192/125289164-98b28c80-e327-11eb-9b7e-8c608d01b77e.png)
https://vk.com/app6909581#VktXZWJBcHBTaG93TmF0aXZlQWRzQCU3QiUyMmFkX2Zvcm1hdCUyMiUzQSUyMnByZWxvYWRlciUyMiU3RA

**Comment by ilyapishchulin** [comment]
Спасибо, поправили
