### ISSUE TITLE
Корректная поддержка VKWebAppShowSubscriptionBox

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#251]
Использую `@vkontakte/vk-bridge@2.4.4` и нужно игроку оформить подписку.

Cудя по всему в текущей реализации это не возможно. 
Есть упоминание "VKWebAppShowSubscriptionBox" в `DESKTOP_METHODS` ([src\bridge.ts](https://github.com/VKCOM/vk-bridge/blob/master/src/bridge.ts)).

Но в `RequestPropsMap` ([src\types\data.ts](https://github.com/VKCOM/vk-bridge/blob/master/src/types/data.ts)) он не описан. Получается нельзя нормально вызвать
`bridge.supports("VKWebAppShowSubscriptionBox")`
и 
`bridge.send("VKWebAppShowSubscriptionBox", ...)`
так как в `RequestPropsMap` нет ключа "VKWebAppShowSubscriptionBox". 

Так же вопрос, будут ли методы `supports` и `send` c  "VKWebAppShowSubscriptionBox" работать, если использовать анонимные вызовы (обойти контроль типов в TS)?

Как понимаю, если в RequestPropsMap добавить ключ и параметры для VKWebAppShowSubscriptionBox, то всё должно начать работать. Так ли это? Если да, то я подготовлю PR.

**Comment by putyavka** [comment]
Всегда есть такой workaround для пока ещё не добавленных методов:
`vkBridge.sendPromise('VKWebAppShowSubscriptionBox' as any ...`

А `vkBridge.supports`, как я понимаю, нужен для проверки наличия метода на текущей платформе (есть методы, которые работают только Android и/или iOS)

**Comment by doterax** [comment]
Есть ли новости по этому багу?

**Comment by ilyapishchulin** [comment]
VK Bridge это просто шина для отправки запросов, если посмотреть код глубже, то можно понять, что никаких обработчиков нет. Можно спокойно поставить any

**Comment by doterax** [comment]
Ну так оно и работает у нас сейчас. Но выглядит неаккуратненько :)
