### ISSUE TITLE
Метод закрытия приложения

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#255]

**Comment by ilyapishchulin** [comment]
Добрый день, о чем этот issue, есть метод VKWebAppCloseApp

**Comment by eolme** [comment]
@ilyapishchulin, #253
> Спасибо за ишью, это задуманное поведение для события

**Comment by ilyapishchulin** [comment]
Верно понял, что хочется иметь параметр, который будет закрывать без сохранения в кеше?

**Comment by eolme** [comment]
VkWebAppClose сворачивает в кэш, название совершенно не соответствует тому что должно делать - issue закрывается с комментарием - задуманное поведение.

Это новый issue с новым методом ЗАКРЫТИЯ приложения.

**Comment by kuhel** [comment]
Событие сворачивает WebView приложения, таков Lifecycle на клиенте. В данный момент пересматривать не думали. Возможно описание сценария использования полного закрытия приложения с выгрузкой из кэша поможет понять, почему надо пересмотреть поведение и ввести дополнительный параметр

**Comment by ilyapishchulin** [comment]
@eolme, поделишься сценарием или можно закрывать issue?

**Comment by eolme** [comment]
@ilyapishchulin сценарий закрытия приложения

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
