### ISSUE TITLE
Неверное описание VKWebAppСlose в документации

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#256]
Нейминг не соответствует поведению - в нативных клиентах всегда сворачивает и сохраняет в кэше

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
