### ISSUE TITLE
Обработка закрытия пользователем окна VKWebAppShowSubscriptionBox

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#257]
При закрытии окна подписки
![image](https://user-images.githubusercontent.com/4847432/127118260-eb80e3a6-3104-4b46-957a-8608dc3377a7.png)
Получаю сообщение об ошибке вида
```
{
	"detail": {
		"type": "VKWebAppShowSubscriptionBoxFailed",
		"data": {
			"error_type": "client_error",
			"error_data": {
				"error_code": 4,
				"error_reason": "User denied"
			},
			"request_id": 3
		}
	}
}
```
Если серверный скрипт обратного вызова вернет завершится аварийно, то я получу такую же ошибку. По факту, я не могу отличить нормальное закрытие окна пользователем и ошибку серверного взаимодействия.

**Comment by doterax** [comment]
то же самое происходит и с `VKWebAppShowOrderBox`

**Comment by ilyapishchulin** [comment]
Добрый день, верно понял, проблема в m.vk.com и vk.com?

**Comment by doterax** [comment]
> Добрый день, верно понял, проблема в m.vk.com и vk.com?

Основной тест проводили на vk.com и на нем ошибка проявляется.

**Comment by andrievskiy** [comment]
Добрый день, предоставьте, пожалуйста, id игры
Также по поводу VKWebAppShowOrderBox, проверьте, пожалуйста. актуальность, сейчас при ошибке получения данных товара возвращается
```
{"error_type":"client_error","error_data":{"error_code":20,"error_reason":"Unknown error"}}
```

**Comment by andrievskiy** [comment]
Да, все закрытия пользователем будут приходить как ошибка
```
"error_code": 4,
"error_reason": "User denied"
```

Документацию поправим, спасибо что обратили внимание

**Comment by doterax** [comment]
Понял.
