### ISSUE TITLE
Быстрое закрытие окна, приводит к вечному ожиданию промиса.

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#258]
К примеру если сделать так:
```
const data = await vkBridge()
	.send("VKWebAppShowOrderBox", { /* */ });
```
или так:
```
const data = await vkBridge()
	.send("VKWebAppShowSubscriptionBox", { /* */ });
```
но в момент загрузки окна сделать клик, то мы вечно будем ждать завершения промиса.

При повторе, сделайте элемент который при клике откроет окно, но в приложении повторяя делайте на нем даблклик. 
То есть, первый клик должен инициировать открытие, а последующий клик проходит по системному затемнению, и останавливает загрузку окна, но не резолвит промис. И следующая строчка после await никогда не будет выполнена.

Предполагаю, что подобное поведение есть во всех окнах.

**Comment by ilyapishchulin** [comment]
Добрый день, на какой платформе замечено такое поведение?

**Comment by doterax** [comment]
Тест был на vk.com, но нужно так же убедится что и на мобильной платформе этого бага нет.

**Comment by doterax** [comment]
Добрый день. Есть понимание, когда это будет исправлено?

**Comment by ilyapishchulin** [comment]
На следующей неделе постараемся пофиксить

**Comment by ilyapishchulin** [comment]
Проблему воспроизвести не смогли, можете прислать скринкаст с воспроизведением?

**Comment by ilyapishchulin** [comment]
Поправили, спасибо за ишью

**Comment by doterax** [comment]
Не вижу в мастере коммитов с правками. Что нужно сделать чтобы исправить это у нас? Или проблема внешняя?

**Comment by ilyapishchulin** [comment]
VK Bridge это шина, хендлер обрабатывается внешне. Всё должно заработать без обновления

**Comment by doterax** [comment]
Перепроверили, ошибка больше не воспроизводится.

Спасибо за исправление.
