### ISSUE TITLE
VKWebAppShowSubscriptionBox не шлёт ни один коллбек, если автоматически подтвердили платеж

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#259]
Как повторить:

В настройках игрока, убедится, что стоит автоматическая оплата в играх:

![image](https://user-images.githubusercontent.com/4847432/128687389-bb1a6f21-dc11-4c44-930d-f44a7938b9c9.png)

Если, этого пункта нет, то в мобильной версии Vk зайти в любую игру и сделать в ней платеж. В окне подтверждения платежа, убедится, что стоит такая галка:
![image](https://user-images.githubusercontent.com/4847432/128688166-6555fde9-65e2-48fa-adf7-cbd6cd07b5ba.png)

После того, как убедились, что стоит автоматическая оплата в играх, при игре в браузере, нужно исполнить такой код:
```
vkBridge()
	.subscribe((message) =>
	{
                console.log(`[Bridge] onEvent(${JSON.stringify(message)})`);
	});


const result = vkBridge()
	.send('VKWebAppShowSubscriptionBox', {...})
	
console.log(`[Bridge] Result of send('VKWebAppShowSubscriptionBox', ...) => ${JSON.stringify(result)})`);
```

На экране произойдет автоматическая подписка, в левом нижнем углу мы видим подтверждение этому, серверный коллбек вызвался корректно.

Но, ни событие не вызвалось на которое подписались (subscribe), ни промис не отрезолвился (в логе нет `[Bridge] Result of send`)

Ожидаю что: и событие вызовется и промис завершится.

**Comment by ilyapishchulin** [comment]
Проблема в vk.com и m.vk.com, правильно понял?

**Comment by doterax** [comment]
> Проблема в vk.com и m.vk.com, правильно понял?

Основная платформа, на которой это тестировалось, это vk.com. Но, для правильного воссоздания бага, тут нужно взаимодействие и с мобильным приложением и из мобильного приложения (Android) сделать платеж и в нем включить галку об автоплатеже. Как это сделать по другому - мы не нашли.

**Comment by andrievskiy** [comment]
Добрый день, можете, пожалуйста указать id игры, где у вас возникает проблема? и шаги воспроизведения именно в игре? Есть ли у подписки, которую вы оформляете триал период?

**Comment by ilyapishchulin** [comment]
Поправили, спасибо за ишью

**Comment by doterax** [comment]
Не вижу в мастере коммитов с правками. Что нужно сделать чтобы исправить это у нас? Или проблема внешняя?

**Comment by ilyapishchulin** [comment]
VK Bridge это шина, хендлер обрабатывается внешне. Всё должно заработать без обновления

**Comment by doterax** [comment]
Перепроверили, всё сработало. 

Теперь, даже если включена автоматическая оплата, покупка подписки спрашивает подтверждение.

Спасибо за исправление.
