### ISSUE TITLE
[Feature] Дополнительные поля в VKWebAppGetGroupInfo

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#266]
Интересуют поля `can_message` и `is_messages_blocked`, тк довольно частый кейс проверки может ли пользователь писать сообществу и наоборот.

**Comment by ilyapishchulin** [comment]
Спасибо, рассмотрим

**Comment by Pronin-vk** [comment]
Спасибо за обращение, рассмотрели в команде платформы, пока не планируем реализовывать данный функционал.
