### ISSUE TITLE
VKWebAppOpenPayForm не принимает поля description (desktop only) и data

### ISSUE THREAD

**Issue by Mkolba** [VKCOM/vk-bridge#269]
При использовании следующего куска кода в десктопной версии ВК отображается форма **без** комментария, хотя на мобильных устройствах всё работает должным образом.

```js
const params = {
        'description': `Оплата тарифного плана.`,
        'group_id': 1,
        'amount': 1
};

bridge.send("VKWebAppOpenPayForm", {app_id: 1, action: "pay-to-group", params: params }).then(resp => {});
```

Кроме того, в [документации](https://vk.com/dev/vk_pay_actions) сказано, что при использовании action: "pay-to-group" можно указать поле data с произвольными параметрами, однако фактически это поле также не поддерживается, ибо до сервера оно не доходит.

```js
const params = {
        'description': `Оплата тарифного плана.`,
        'data': {'foo': 'bar'},
        'group_id': 1,
        'amount': 1,
};

bridge.send("VKWebAppOpenPayForm", {app_id: 1, action: "pay-to-group", params: params }).then(resp => {});
```
![image](https://user-images.githubusercontent.com/49096456/134358561-da2913aa-bf96-4d49-ae96-311369862933.png)

**Comment by ilyapishchulin** [comment]
Сейчас проблема с описанием еще наблюдается?

**Comment by Mkolba** [comment]
Да, наблюдается

**Comment by ilyapishchulin** [comment]
Можете сделать скринкаст проблемы с описанием?

**Comment by Mkolba** [comment]
https://user-images.githubusercontent.com/49096456/134904818-49eeaaf3-a4d8-46aa-9fcb-57622b009bd5.mp4

Часть кода, отвечающая за открытие окна оплаты
```js
  pay = (amount) => {
    const params = {
      'description': `Пополнение баланса [#${this.props.globState.selectedBot.id}]\n\nНе изменяйте этот текст, иначе платеж может потеряться.`,
      'group_id': 204763562,
      'amount': amount
    }
    this.props.goBack();
    bridge.send("VKWebAppOpenPayForm", {app_id: 7693720, action: "pay-to-group", params: params }).then(resp => {

    });
  }
```

**Comment by ilyapishchulin** [comment]
В песочнице не смог воспроизвести

**Comment by Mkolba** [comment]
Можно ссылку на песочницу?

**Comment by Mkolba** [comment]
Тоже посмотрел, действительно работает, но не во всех случаях. Например, если указать в тексте "#", то описание будет пустым (в песочнице почему-то вообще ломаются все поля и открывается форма перевода 0 рублей неизвестно куда с пустым описанием)

![image](https://user-images.githubusercontent.com/49096456/134930922-267c627c-a907-4b8b-a4ce-befbd80b4071.png)
![image](https://user-images.githubusercontent.com/49096456/134931227-550b3232-073a-4706-9da2-f2a2317ccf09.png)

**Comment by Mkolba** [comment]
Также перестал работать перенос строк в description
![image](https://user-images.githubusercontent.com/49096456/135038671-656734d3-6d9d-428d-8c37-48ebb73ed7f4.png)
![image](https://user-images.githubusercontent.com/49096456/135038696-59ca194b-d520-4414-9e4b-55b5a4b7a38c.png)

**Comment by ilyapishchulin** [comment]
Давайте разделим ишью про параметр в callback и description, description починим

**Comment by ilyapishchulin** [comment]
Описание поправили

**Comment by Mkolba** [comment]
Да, описание работает, спасибо. 

А что с callback параметром, стоит ждать фикса?

**Comment by ilyapishchulin** [comment]
Стоит ждать, но не так быстро как описание, к сожалению

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
