### ISSUE TITLE
VKWebAppCreateHash не совпадают значения hash

### ISSUE THREAD

**Issue by AlexanderBYSO** [VKCOM/vk-bridge#271]
Доброго времени суток!

Клиент:
`vkBridge.send("VKWebAppCreateHash")
        .then(data => {
                $.ajax({ 
                    type: "POST",  
                    url: "/videoViewed",
                    data: "id=" + user.id +
                        "&ts=" + data.ts +
                        "&hash=" + data.hash,
                    success: function(html){
                        console.log(html)
                    } 
                })
                console.log(data.hash)
    })
    .catch(error => console.log(error));
})`

Сервер:

`$hash_params = [
        'ts' => $_POST['ts'],
        'hash' => $_POST['hash']
    ];
$client_secret = '********';
$hash = $hash_params['hash'];
 unset($hash_params['hash']);

// Сортируем массив по ключам.
 ksort($hash_params);

// Формируем строку вида param_name1=value&param_name2=value.
$sign_params_query = http_build_query($hash_params);

// Получаем хеш-код от строки, используя защищеный ключ приложения (метод HMAC).
$sign = rtrim(strtr(base64_encode(hash_hmac('sha256', $sign_params_query, $client_secret, true)), '+/', '-_'), '=');

echo($sign);`

По итогу, хеши не равны.
Пробовал и с параметром 'request_id', аналогичная ситуация.

Проверял аналогичный хеш при проверке подписи параметров - там все сходится.

Библиотеку подключаю:
`<script src="https://unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js"></script>`

**Comment by MrZillaGold** [comment]
Мне кажется это возникает из-за этой проблемы
https://github.com/VKCOM/vk-bridge/issues/275

**Comment by ilyapishchulin** [comment]
Кажется, что не актуально

**Comment by MrZillaGold** [comment]
@ilyapishchulin Использую реализацию для node.js такую же как для проверки параметров запуска, но с несколькими изменениями - не работает, может я что-то делаю не так? Сама подпись параметров проверяется успешно.

```js
import crypto from 'crypto';
import { URLSearchParams } from 'url';

const app_id = 1;
const user_id = 1;
const payload = '1';
const ts = 1;
const sign = '1';

console.log(
    checkSign({
            app_id,
            user_id,
            payload,
            ts
        }, sign)
);

function checkSign(query: string | Record<string, any>, queryHash?: string): boolean {
    const params = new URLSearchParams(query);

    const ordered: Record<string, any> = {};

    [...params.entries()]
        .sort()
        .forEach(([key, value]) => {
            if (key.startsWith('vk_') || queryHash) {
                ordered[key] = value;
            }
        });

    const orderedQuery = new URLSearchParams(ordered)
        .toString();

    console.log(orderedQuery); // app_id=8021524&payload=1&ts=1639883827&user_id=233731786

    const hash = createHmac(orderedQuery);

    console.log(hash, queryHash);

    return hash === (queryHash || params.get('sign'));
}

function createHmac(content: string): string {
    return crypto
        .createHmac('sha256', process.env.SECRET_KEY as string)
        .update(content)
        .digest()
        .toString('base64')
        .replaceAll('+', '-')
        .replaceAll('/', '_')
        .replaceAll('=', '');
}
```

**Comment by ilyapishchulin** [comment]
Спасибо, поправил документацию. В мапе на месте payload должен остаться request_id.
Итоговая строка будет: `app_id=8021524&request_id=1&ts=1639883827&user_id=233731786`

https://dev.vk.com/bridge/VKWebAppCreateHash
