### ISSUE TITLE
VKWebAppCreateHash возвращает разные имена полей на разных платформах

### ISSUE THREAD

**Issue by Melodyn** [VKCOM/vk-bridge#275]
В десктопной версии и iOS клиенте хэш хранится в свойстве `hash`:
![десктоп](https://user-images.githubusercontent.com/26752238/140609526-9eb3331f-bf3b-4408-af6d-860cc06522cb.png)

В мобильном клиенте Android хэш хранится в свойстве `sign`:
![Android](https://user-images.githubusercontent.com/26752238/140609600-8410f0e5-ee91-4019-a958-c457aa05307a.png)

Должно всегда возвращаться поле `hash`, согласно документации: https://vk.com/dev/vkbridge/vkwebappcreatehash

Воспроизводится в песочнице: https://vk.com/app6909581#VktXZWJBcHBDcmVhdGVIYXNoQCU3QiU3RA==

Ошибка со стороны VKBridge или документации?

**Comment by catofsof** [comment]
Также ts приходят с разными типами.

**Comment by ilyapishchulin** [comment]
Исправлено
https://vk.com/vkappsdev?w=wall-166562603_3884
