### ISSUE TITLE
Некорректно форматируется ссылка на приложение в VKWebAppShowWallPostBox

### ISSUE THREAD

**Issue by semperhomolupus** [VKCOM/vk-bridge#276]
Пытаюсь из vk mini app вызвать VKWebAppShowWallPostBox, в attachments передаю ссылку на приложение https://vk.com/app7999335, сайт при публикации поста меняет ее на https://vk.com/vk.com/app7999335 (два раза vk.com/).

В тестовой среде воспроизводится
https://vk.com/app6909581

http://joxi.ru/KAgGvDgfEMZ0MA

**Comment by ilyapishchulin** [comment]
Спасибо, посмотрим

**Comment by ilyapishchulin** [comment]
Поправили
