### ISSUE TITLE
Ломается кодировка русских символов в секции Storage.

### ISSUE THREAD

**Issue by reyzitwo** [VKCOM/vk-bridge#277]
1. Вызываем метод StorageSet, указываем в value русские символы.
2. Вызываем метод StorageGet.

Кириллица отображается с вопросами.

https://user-images.githubusercontent.com/73870113/143468053-ddd622cc-783e-457d-921c-b221531509c9.mp4

**Comment by ilyapishchulin** [comment]
Не воспроизвелось

![d-cjQRCYbgs](https://user-images.githubusercontent.com/45998835/145958467-1f3c1458-7af8-424a-9b4c-bae7bb22d0f8.jpg)

**Comment by reyzitwo** [comment]
Все также воспроизводится, в других сервисах, которые сохраняют кириллицу в VK Storage тоже воспроизводится
![Screenshot_20211214-153151_VK](https://user-images.githubusercontent.com/73870113/145981593-5e115940-74e5-4020-86ee-49f33f8b59ee.jpg)

**Comment by reyzitwo** [comment]
Сейчас выяснил, что на другом аккаунте ВК не воспроизводится ¯\_(ツ)_/¯
На основном все ещё актуально

**Comment by ilyapishchulin** [comment]
Дайте user_id аккаунта, где воспроизводится, пожалуйста

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
