### ISSUE TITLE
Отсутствует тип VKWebAppCreateHash в RequestPropsMap

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/vk-bridge#279]

**Comment by ilyapishchulin** [comment]
https://github.com/VKCOM/vk-bridge/blob/master/src/types/data.ts#L926

**Comment by SkyGopnik** [comment]
@ilyapishchulin почему на npm последняя версия стоит 2.4.8?

**Comment by ilyapishchulin** [comment]
Там есть версия 2.5.1, если устанавливать руками. Тег поправим в следующем релизе

**Comment by SkyGopnik** [comment]
То что она там есть я теперь вижу, но кто же знал что она была тогда)

> Там есть версия 2.5.1, если устанавливать руками. Тег поправим в следующем релизе
