### ISSUE TITLE
[VKWebAppGetCommunityToken] Не приходит поле scope в ответе при получении токена группы на iOS

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/vk-bridge#281]
На ПК данное значение прилетает, как и при получении токена пользователя. 

UPD: когда появится точная информация, можно мержануть (https://github.com/VKCOM/vk-bridge/pull/272)

**Comment by ilyapishchulin** [comment]
Спасибо, посмотрим

**Comment by ilyapishchulin** [comment]
Исправлено, спасибо за MR
