### ISSUE TITLE
VKWebAppShowNativeAds не учитывает высоту iframe

### ISSUE THREAD

**Issue by afarber** [VKCOM/vk-bridge#283]
Добрый вечер, с наступающим новым годом!

У меня [iframe-приложение для Web](https://vk.com/app5442212) с относительно высоким iframe (820 на 4000 пикселей), потому что много контента (под игрой показаны статистика игроков, игровой словарь, загадка дня, ...) и когда я вызываю VKWebAppShowNativeAds, то реклама показывается внизу, вне экрана

Пользователи видят только темный экран, а рекламу видно только если начать скроллить вниз (см. видео)

Прошу Вас исправить эту ошибку и использовать `Math.min(window.innerHeight, <высота iframe>) / 2` для показа рекламы.

Или `Math.min(screen.height, <высота iframe>) / 2` 

https://user-images.githubusercontent.com/1884458/147838658-0f8488a3-0eda-42eb-9807-25c26264004e.mov

**Comment by afarber** [comment]
На Одноклассниках похожая проблема - и они обещают исправить:

![image](https://user-images.githubusercontent.com/1884458/147926919-c4e2773e-6871-423b-825f-5fb2c86e7c38.png)

На Yandex Games такой проблемы нет, у них реклама в середине экрана, несмотря на мой высокий iframe:

![image](https://user-images.githubusercontent.com/1884458/147927032-c4e5317e-3d62-4d80-97a9-d52fd05c140a.png)

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
