### ISSUE TITLE
VKWebAppCreateHash всегда возвращает ошибку, если приложение - игра

### ISSUE THREAD

**Issue by Jekamajor** [VKCOM/vk-bridge#285]
Здравствуйте!

Платформа: встраиваемое приложение.
Тип: игра.
В настройках приложения в качестве "адрес IFrame" указан URL адрес до test.html файла (см ниже). 

При этих условиях метод VKWebAppCreateHash всегда возвращает ошибку. 
В сетевых логах видно, что запрос идет на https://api.vk.com/method/apps.getSecretHash?v=5.133&client_id=xxxx, а в ответ приходит JSON: `{"error":{"error_code":15,"error_msg":"Access denied","request_params":[{"key":"v","value":"5.133"},{"key":"client_id","value":"xxxx"},{"key":"method","value":"apps.getSecretHash"},{"key":"oauth","value":"1"},{"key":"app_id","value":"xxxx"}]}}`

Проблема воспроизводится с разных ПК, с разных IP адресов, с разных аккаунтов VK. 
Другие методы VK Bridge при этом работают исправно. 

Если указать тип приложения "VK Mini Apps" вместо "Игра", то метод работает корректно. 
Исправьте, пожалуйста.

Простой test.html для воспроизведения:
``` 
<script src="https://unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js"></script>

<script>  
  console.log('VK test');
  vkBridge.send('VKWebAppInit');
  
  vkBridge
  .send('VKWebAppCreateHash')
  .then(data => {
	console.log('VKWebAppCreateHash_response', data);
  })
  .catch(
	error => console.log('VKWebAppCreateHash_error', error);
  );
</script>
```

**Comment by ilyapishchulin** [comment]
Спасибо, поправили, ближе к вечеру можно проверять
