### ISSUE TITLE
VKWebAppGetLaunchParams возвращает api_error при вызове на Андроиде

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#286]
Для получения авторизационного токена вызываю `VKWebAppGetLaunchParams `
Из браузера всё работает как и ожидается, на андроиде из приложения получаю ошибку:
`{"error_type":"api_error"}`
При этом bridge.supported("VKWebAppGetLaunchParams") возвращает true

UPD.
Возможна ли эта проблема из-за того, что в мобильном приложении я загружаю скрипт
`<script src="https://unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js"></script>`

**Comment by ilyapishchulin** [comment]
Какой тип у приложения? Игра?

**Comment by doterax** [comment]
Да. Игра.

**Comment by ilyapishchulin** [comment]
Это событие доступно только для мини-приложений
