### ISSUE TITLE
bridge.supports("VKWebAppCheckNativeAds") возвращает false на десктоп платформе

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#287]
Согласно [документации](https://vk.com/dev/vkbridge/vkwebappchecknativeads), метод VKWebAppCheckNativeAds должен быть доступен на десктоп платформе.

![image](https://user-images.githubusercontent.com/4847432/149918805-25caa179-a9d6-42a6-839d-37a7cbe22138.png)

но bridge.supports("VKWebAppCheckNativeAds) возвращает false на десктопе, что приводит к воркэраундам в клиентском коде. Я для десктоп платформы просто проигнорировал результат bridge.supports и вызвал этот метод так, как будто он есть, и всё отработало как надо.

Выглядит так, как будто его забыли добавить его в список поддерживаемых десктопных методов. Если это так, то я сейчас готовлю пул реквест.

**Comment by ilyapishchulin** [comment]
Спасибо!
