### ISSUE TITLE
vk-bridge конфликтует с платформой Facebook Instant Games.

### ISSUE THREAD

**Issue by doterax** [VKCOM/vk-bridge#290]
Если разрабатывать игру, которая поддерживает несколько платформ, то возможно натолкнутся на ситуацию, когда Facebook перестаёт принимать сборки. Проблема возникает при автоматической проверке.

Экран с ошибкой выглядит так:
![image](https://user-images.githubusercontent.com/4847432/151396140-76c9f86e-100e-4496-9909-499d9dabb5f5.png)

На английском это звучит так:

> Games must use the Instant Games SDK properly and should not call private methods directly.

После изысканий, мы нашли, что проблема в строке
`parent.postMessage`
Видимо, автоматическая проверка в Facebook обнаруживает эту подстроку и считает, что мы нарушаем что-то, и не пропускает эту сборку.

В качестве выхода из ситуации, некоторые команды у нас после FB билда, находят подстроку "parent.postMessage" и заменяют её на что-то другое типа "parent.someRandomName" и это помогает.

Я же предлагаю, подружить vk-bridge с Fb переработав этот кусок кода в файле bridge.ts
```
    // Sending data through web bridge
    else if (IS_WEB) {
      parent.postMessage(
        {
          handler: method,
          params: props,
          type: 'vk-connect',
          webFrameId,
          connectVersion: version,
        },
        '*'
      );
    }
```

Вызывать не явно parent.postMessage, а получить ссылку на метод, и потом его вызвать.

С вашего позволения, я оформлю пуллреквест с этой правкой.

**Comment by ilyapishchulin** [comment]
Я бы предложил не нести такой хак в библиотеку. Если он вам нужен отдельно, то лучше форкнуть проект и собрать личную версию

**Comment by doterax** [comment]
С этой проблемой сталкиваются все команды, которые делают игры на несколько платформ. Тут проблема особо не в хаке, а во времени, которое затрачивается на поиск причины, по которой фейсбук начинает отклонять сборку.

**Comment by Moyous** [comment]
Привет! @doterax идея затащить воркэраунд, чтобы всем не приходилось вручную хакать в таких кейсах, хорошая. Давай попробуем определить `webBridge` по аналогии с `iosBridge`, чтобы вызывать на месте как `webBridge.postMessage` вместо `parent.postMessage`. Внутри определения можно будет заодно и проверок вставить на наличие `parent`. Если это поможет решить вашу проблему и ошибки на ревью у FB пройдут, то и славно, вкатим в таком виде.

**Comment by ilyapishchulin** [comment]
Спасибо, опубликовали
