### ISSUE TITLE
Поддержка передачи query параметров в VKWebAppOpenApp

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/vk-bridge#292]
Будет полезно для передачи таких параметров как `ref` и тп.

**Comment by ilyapishchulin** [comment]
Какие еще параметры хочется передавать? vk_ref это место открытия родительского аппа, но никак не внутреннего

**Comment by MrZillaGold** [comment]
При запуске спец. проектов, есть необходимость перенаправления пользователя в другие приложения, при перенаправлении из приложения A в B передаем значение ref, тем самым показывая что пользователь пришел из приложения A. Нет необходимости изменять vk_ref, я точно не знаю трекается ли кастомный ref вообще, но задача с передачей параметра была, пришлось встраивать ссылку в саму кнопку.

**Comment by ilyapishchulin** [comment]
Мы не учитываем кастомные рефы, если это спец. проект, то скорей всего у него есть аналитика в виде utm меток, которые передаются в хеше. Поддерживать передачу query параметров, как и их поддержку для передачи в приложения мы не планируем
