### ISSUE TITLE
VKWebAppGetAuthToken возвращает unknown error

### ISSUE THREAD

**Issue by Mkolba** [VKCOM/vk-bridge#293]
Вызов осуществляется следующим образом:
```js
bridge.send("VKWebAppGetAuthToken", {"app_id": 7693720, "scope": "groups"}).then(resp => {...})
```
![image](https://user-images.githubusercontent.com/49096456/153445620-93200a92-2029-4797-a0c4-d5e0cd6399b8.png)

Актуально только на некоторых устройствах, у большинства пользователей все работает как задумано.
Отчет с подробностями в баг-трекере: https://vk.com/bug346701

**Comment by ilyapishchulin** [comment]
Поправили в последней релизной версии, спасибо за ишью
