### ISSUE TITLE
Сниппет не подгружается в модальном окне VKWebAppShowWallPostBox

### ISSUE THREAD

**Issue by Jekamajor** [VKCOM/vk-bridge#298]
Здравствуйте! 
Тип приложение - игра.
В момент, когда я предлагаю игроку опубликовать ссылку на его стене с помощью метода VKWebAppShowWallPostBox , сниппет с моего сайта не подгружается, хотя тег vk:image на странице присутствует. Сниппет на самой стене уже подгружается позже? после публикации. Но в самом модальном окне "Добавление записи на стену" изображения нет - и это выглядит плохо. 

Вызываю метод VKWebAppShowWallPostBox с параметрами {"message": "Тест ", "attachments": "https://stopvideo.net/share/VK/3/160/3cf273b86748e93eba10c31b84ac5731"}

Заметил, что сниппет появляется в модальном окне сразу, только если ссылка в домене vk.com, а с других доменов сниппет не тянет.
Возможно ли это исправить?

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
