### ISSUE TITLE
Не приходит филд `appearance` на сайте vk.com и m.vk.com

### ISSUE THREAD

**Issue by ItzNeviKat** [VKCOM/vk-bridge#299]
Для определения темы обычно использую:
```typescript
subscribe(({ detail: { type, data } }) => {
  if (type === 'VKWebAppUpdateConfig' && data.appearance)
    setAppearance(data.appearance as Appearance);
});
```
Но на сайте приходит только `scheme`:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/24193020/165109943-f2d22b6f-7bab-4ee8-bc8d-e3f51aa86b0c.png">

что является **deprecated** в VKUI.

**Comment by ilyapishchulin** [comment]
Исправили, спасибо

**Comment by ItzNeviKat** [comment]
Если отправить событие `VKWebAppGetConfig`, то `appearance` приходит, а если ловить `VKWebAppUpdateConfig`, то нет:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/24193020/168969585-12d6a132-87ed-45c5-aa35-d977e64b326a.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/24193020/168969493-12cbbc00-afc5-4699-9d69-1a1b4f8cb8a4.png">

**Comment by SevereCloud** [comment]
Еще типизацию надо бы поправить

**Comment by ilyapishchulin** [comment]
Спасибо, поправили типизацию в 2.7.0 и поправили UpdateConfig, теперь он аналогичен GetConfig
