### ISSUE TITLE
Ошибка при генерации хеша в мобильном клиенте (VKWebAppCreateHash)

### ISSUE THREAD

**Issue by ttempaa** [VKCOM/vk-bridge#306]
Если на мобильном клиенте вызывать событие «VKWebAppCreateHash» с передачей «payload», то возвращается ответ без поля «payload».

При этом, проверить сгенерированный хеш не получается, даже при ручном добавлении «payload».

<details>
<summary>Ответ на vk.com</summary>
<img src="https://user-images.githubusercontent.com/79640477/178465170-b9b04e78-b0d1-4475-a1b0-29a5de98cd56.png">
</details>

<details>
<summary>Ответ на m.vk.com</summary>
<img src="https://user-images.githubusercontent.com/79640477/178465619-dbdaf13f-2420-4763-84ef-d85a3cf6fafe.png">
</details>

<details>
<summary>Ответ на мобильном клиенте</summary>
<img src="https://user-images.githubusercontent.com/79640477/178465900-10383d69-6e90-4c1a-a239-28ba6e149351.png">
</details>

**Comment by ilyapishchulin** [comment]
Установи, пожалуйста, последнюю версию клиента и попробуй там

**Comment by ttempaa** [comment]
Да, оказывается проблема была в этом. Не подумал что это могло происходить из-за стороннего мобильного клиента.

Спасибо :)
