### ISSUE TITLE
VKWebAppGetGeodata возвращает устаревшие данные

### ISSUE THREAD

**Issue by vladyoslav** [VKCOM/vk-bridge#307]
Метод VKWebAppGetGeodata получает данные только один раз, при повторных вызовах возвращает первоначально полученные значения, т.е. устаревшую информацию. 

Уже были подобные ишью (#223, #203), но они открыты больше года назад, а проблема всё ещё не решена, под угрозой стоит жизнь приложения.
Из #223:
> "Если на фоне каждый раз открывать какую-либо карту, то геоданные обновляются и в ВК. Также они обновляются, если поменять геоданные через фейк GPS."

Да, у меня тоже наблюдается такое поведение. На "Кешируется на стороне Google сервисов" (#203) возник такой же вопрос, что и у автора ишью, почему же у других приложений всё нормально?

> Нужен стабильный кейс для воспроизведения. Примеры устройств и побольше конкретики

- Приложение для воспроизведения: https://vk.com/app8217155
- Репозиторий: https://github.com/vladyoslav/vkma-geolocation-problem
- Вызов VKWebAppGetGeodata [здесь](https://github.com/vladyoslav/vkma-geolocation-problem/blob/main/src/pages/home.tsx)

Проверялось на POCO X3 Pro Android 11, в нативном приложении и в mvk.

**Comment by evtn** [comment]
This is sad👍

**Comment by TheBakerCat** [comment]
Воспроизводится. POCO X3, Android 11.

**Comment by ItzNeviKat** [comment]
Подтверждаю. iPhone XS Max, отхожу в другое место и перезагружаю - только тогда обновляется. Пробовал открывать в фоне Яндекс.Карты, геопозиция всё равно обновляется только после перезагрузки страницы.

**Comment by dndrheadof** [comment]
Хитрый ксими redmi note 6 pro, 12 андроид, воспроизводится

**Comment by eolme** [comment]
Воспроизводится на Pixel 5

**Comment by ilyapishchulin** [comment]
Спасибо, мы исправили проблему в m.vk.com версии. Для Android приложения посмотрели ещё раз, запрашиваем самое актуальное состояние, дальше дело за гугл сервисами.

Если у вас проблема воспроизводится, то нужно собрать побольше данных, а именно: название устройства, версия android и видео показывающее, что в другом нативном приложении всё работает корректно, а в приложении ВКонтакте геопозиция отдаётся некорректно

**Comment by vladyoslav** [comment]
Сегодня подробнее изучил проблему, заметил, что точно такое же поведение наблюдается у метода Geolocation API [`Geolocation.getCurrentPosition()`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) (при его использовании данные тоже как будто кешируются системой, даже если в параметрах указать указать `maximumAge: 0`, что должно отключать кеширование). Проверил метод подписки на изменение геолокации [`Geolocation.watchPosition()`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition) — с ним всё работает идеально. Т.е. искомую проблему, скорее всего, можно решить только добавлением альтернативы для [`Geolocation.watchPosition()`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition) в bridge. Стоит ли создавать под это предложение отдельное ишью?

**Comment by ilyapishchulin** [comment]
Да, давай закроем текущее ишью и все остальные. Заведем новое с методами отслеживания гео, чтобы информация сама передавалась в апп
