### ISSUE TITLE
При восстановлении приложения из кэша не приходит VKWebAppUpdateConfig

### ISSUE THREAD

**Issue by eolme** [VKCOM/vk-bridge#31]
При смене темы, пока сервис свернут, не приходит `VKWebAppUpdateConfig`. Предлагаю после `VKWebAppViewRestore` присылать `VKWebAppUpdateConfig`.

**Comment by danakt** [comment]
@eolme почему? В каких кейсах это будет нужно?

**Comment by LazyTechwork** [comment]
Некоторые пользователи изменяют цветовую схему после выхода из приложения, мы должны это отслеживать, поэтому нужно, чтобы присылалась конфигурация клиента
