### ISSUE TITLE
src/types/data.ts/RequestPropsMap не содержит метод VkWebAppGetAds

### ISSUE THREAD

**Issue by Hermer29** [VKCOM/vk-bridge#319]
https://dev.vk.com/games/monetization/ad/implementation#%D0%9A%D0%B0%D0%BA%20%D0%B2%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C%20%D0%B1%D0%B0%D0%BD%D0%BD%D0%B5%D1%80%20%D0%B2%20%D0%B8%D0%B3%D1%80%D1%83 здесь описывается, что через node js вполне реально вызывать этот метод, однако этот метод вообще не работает, полагаю он не реализован?

**Comment by anzolo** [comment]
В типах его тоже нет @vkontakte/vk-bridge/dist/types/src/types/bridge.d.ts . Возможно ли актуализировать типы?
