### ISSUE TITLE
Ответ VKWebAppGetGroupInfo не содержит поле type, хотя в типах есть

### ISSUE THREAD

**Issue by alexz9** [VKCOM/vk-bridge#324]
Возвращаемый объект не содержит поле type, где должно указываться группа это или паблик.

При этом в документации поля нет https://dev.vk.com/bridge/VKWebAppGetGroupInfo

В описании типа объекта есть https://github.com/VKCOM/vk-bridge/blob/master/src/types/data.ts
``` ts
export type GroupInfo = {
  id: number;
  name: string;
  screen_name: string;
  is_closed: number;
  type: string;
  is_member: number;
  description: string;
  photo_50: string;
  photo_100: string;
  photo_200: string;
};
```

Прошу добавить это поле, очень надо.

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
