### ISSUE TITLE
Подключить VK Bridge

### ISSUE THREAD

**Issue by Grayr81** [VKCOM/vk-bridge#327]
Здравствуйте.Мне, нужно импортировать игру в вк.но проблема в том, что не получается Подключить VK Bridge

**Comment by quick6response** [comment]
В чем заключается проблема? На чем написана игра?

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
