### ISSUE TITLE
ShowInviteBox закрытия диалога вызывает Диалоговое окно с ошибкой

### ISSUE THREAD

**Issue by Stalkerman2010** [VKCOM/vk-bridge#328]
Любое закрытие диалоговых окон вызванных через VK-bridge вызывает ошибку в браузере ссылка на скриншот [https://sun9-63.userapi.com/impg/HRZu6N7JpXnIgpoUMk6_0HgiIrYiY4hA_LcCeQ/PNrZmHg4shc.jpg?size=856x298&quality=95&sign=cbf3f7364bca237dfb72fc14bc339c8e&type=album](url)

В логах пишут Invoking error handler due to
Script error.  Uncaught TypeError: e.error_data.error_code.toLowerCase is not a function

Вызов метода.
    vkBridge.send("VKWebAppShowInviteBox", {})
    .then((data) => { if (data.result) {console.log(data)}})
    .catch((error) => {console.log(error)});

Пожалуйста, подскажите возможно как-то решить проблему, чтобы не выскакивало диалоговое окно с ошибкой после закрытие окна приглашения друзей ?

**Comment by Stalkerman2010** [comment]
Ошибку исправил, возможно кто-то также ошибется. 
Ошибка выскакивает в браузерной версии 
если подключили
<script src="https://vk.com/js/api/mobile_sdk.js"  type="text/javascript"></script>
а нужно
<script src="https://vk.com/js/api/xd_connection.js?2"  type="text/javascript"></script>

**Comment by Stalkerman2010** [comment]
Однако проблема в мобильной версии осталась. 
Если использовать 
<script src="https://vk.com/js/api/xd_connection.js?2" type="text/javascript"></script> 
То игра не загружается.
Если использовать 
<script src="https://vk.com/js/api/mobile_sdk.js" type="text/javascript"></script> 
то проблема остается при закрытии диалогового окна. 
Script error. Uncaught TypeError: e.error_data.error_code.toLowerCase is not a function

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
