### ISSUE TITLE
[Bug]: модалка `VKWebAppShowSlidesSheet` закрывается со второго клика по кнопке `Пропустить`

### ISSUE THREAD

**Issue by scffs** [VKCOM/vk-bridge#330]
### Описание

Модальное окно `VKWebAppShowSlidesSheet ` закрывается только со второго клика по кнопке `Пропустить`

### Версия

5.2.3

### В каких браузерах воспроизводится проблема?

Firefox & Firefox dev edition & Chrome latest

### Шаги воспроизведения

1. Добавить в проект VKWebAppShowSlidesSheet (можно прям из доки)
2. Нажать `Пропустить` 1 раз

### Ожидаемое поведение

Модалка закрывается

### Скриншоты

https://www.youtube.com/watch?v=z8kp43Stty0

### Пример с воспроизведением

https://www.youtube.com/watch?v=z8kp43Stty0

P.S. в песочнице не открывается модалка, вроде код тот же... [link](https://codesandbox.io/s/quirky-drake-my9z01?file=/src/App.js)

**Comment by SevereCloud** [comment]
[VKWebAppShowSlidesSheet](https://dev.vk.com/bridge/VKWebAppShowSlidesSheet) не относится к [VK Bridge](https://dev.vk.com/bridge/getting-started), а не VKUI. 

---

> P.S. в песочнице не открывается модалка, вроде код тот же...

Библиотека VK Bridge является мостом между приложениями, работающими на стороне пользователя, и клиентской частью ВКонтакте. Она не будет работать вне VK

**Comment by scffs** [comment]
Ой, ок
Там баг к тому же с моей стороны в итоге был..
