### ISSUE TITLE
[VKJS][API]: api didn't allowed 

### ISSUE THREAD

**Issue by AntonRls** [VKCOM/vk-bridge#331]
Здравствуйте.

У меня есть приложение в Mini Apps: https://m.vk.com/app51592359
Если запускать его с vk.com и мобильного клиента, то всё хорошо, но если запускать его из m.vk.com, то иногда появляется ошибка (прикрепил скриншот). Как её можно исправить? При старте приложения вызывается VkWebAppInit
![2023-04-01_09-31-58](https://user-images.githubusercontent.com/74132592/229274180-2b7b53d1-24b0-4021-b6f1-04f91df2ae58.png)

**Comment by Pronin-vk** [comment]
Здравствуйте! Мы обновляем процесс работы с репозиторием vk-bridge. Сейчас мы закрываем все обращения, созданные ранее 01.06.2023. Если проблема еще актуальна, пожалуйста, переоткройте это обращение.
