### ISSUE TITLE
Проблема с методом `VKWebAppGetAuthToken` в android-приложении

### ISSUE THREAD

**Issue by Pashun4ik** [VKCOM/vk-bridge#358]
Метод перестал генерировать токен в android-приложении. С vk.com,m.vk.com всё нормально.

![image](https://github.com/VKCOM/vk-bridge/assets/18473129/51a4ecee-18b5-452c-9cee-190cc963c92e)

Проблема проявляет себя конкрерно с моей страницей (vk.com/ecmascript6)

**Comment by Pashun4ik** [comment]
Игра, в которой прямо сейчас воспроизводиться: https://vk.com/tinyicon

**Comment by Pashun4ik** [comment]
Пофиксили

**Comment by nshvyryaev** [comment]
Добрый день!

Спасибо за обращение. Проблема известна, мы работаем над ее решением.
