### ISSUE TITLE
[Bug]: в `RequestPropsMap` нет `VKWebAppShowSlidesSheet`

### ISSUE THREAD

**Issue by scffs** [VKCOM/vk-bridge#362]
upd
Или всё-таки есть баг
![image](https://github.com/VKCOM/vk-bridge/assets/67464545/bcdf4527-0f47-4b15-925d-cf3c5829727c)

![image](https://github.com/VKCOM/vk-bridge/assets/67464545/2e2b1568-9c3e-4f2e-ac17-1fae19a2db97)

[дока](https://dev.vk.com/bridge/VKWebAppShowSlidesSheet#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80)

**Comment by scffs** [comment]
нет бага

**Comment by Pronin-vk** [comment]
@scffs Доброе утро, проблема еще актуальна ?
Какая версия vk-bridge установлена у вас в проекте?

**Comment by scffs** [comment]
> @scffs Доброе утро, проблема еще актуальна ? Какая версия vk-bridge установлена у вас в проекте?

Привет, я чуть позже обязательно чекну и отвечу

**Comment by scffs** [comment]
> Какая версия vk-bridge установлена у вас в проекте?

на скрине 2.8.3

**Comment by scffs** [comment]
на последней версии как минимум все гуд
