### ISSUE TITLE
[Bug][VKWebAppShowSlidesSheet]: возвращается `cancel` вместо `confirm` при просмотре всех слайдов

### ISSUE THREAD

**Issue by scffs** [VKCOM/vk-bridge#363]
Демка бага:

https://github.com/VKCOM/vk-bridge/assets/67464545/18896b24-e8ce-4bce-be24-b148cdcde8c2

версия 2.7.4
Кстати, на гитхабе последняя версия 2.7.0, но в package 2.7.4
![image](https://github.com/VKCOM/vk-bridge/assets/67464545/2e003f27-6732-46ef-96e6-059be6295ac1)

**Comment by Pronin-vk** [comment]
@scffs Добрый вечер, спасибо за обращение, мы исправляли данный баг, больше не воспроизводится?

**Comment by scffs** [comment]
vrode good
