### ISSUE TITLE
VK-connect не работает в Direct Games

### ISSUE THREAD

**Issue by reetou** [VKCOM/vk-bridge#39]
В Direct Games по какой-то причине VK-connect не может подписаться и отправить инит, в мини аппс все работает норм.

Шаги для воспроизведения:

1. Устанавливаете бойлерплейт https://github.com/VKCOM/create-vk-mini-app с `--zeit` и деплоите на zeit

**В now.json поменяйте `version: 1` на `version: 2`, иначе билдер кинет ошибку**

2. Создаете 2 приложения - Direct Games (встраиваемое приложение) и VK mini apps (встраиваемое приложение)

3. Добавляете урл приложения в вк мини апп и в директ геймс

4. Заходите в каждое.

Я уже сделал это за вас, можно посмотреть тут:

**Mini App**, все работает: https://vk.com/app7288017 
**Direct Games**, вечный лоадинг: https://vk.com/app7287611

**Comment by danakt** [comment]
Спасибо за issue! Разберёмся

**Comment by danakt** [comment]
@reetou на какой платформе ошибка воспроизводится?

**Comment by kuhel** [comment]
В вебе коннект, он же vk bridge на платформе Direct Games не поддержан. Вопросы по этому поводу можно задавать сюда
