### ISSUE TITLE
VKWebAppChangeFragment не присылается

### ISSUE THREAD

**Issue by goodwin74** [VKCOM/vk-bridge#397]
Если зайти в сервис по ссылке (например из чата по сниппету) с хешом, а потом так же без хеша, VKWebAppChangeFragment не присылается хотя сменился и стал пустым. По итогу сервис запущенный в фоне(из кеша) не может узнать что его открыли уже без хеша.

**Comment by minenkov-sergey** [comment]
Встретили такую же проблему. На андроиде точно.

**Comment by Pronin-vk** [comment]
@goodwin74 Добрый день, спасибо за обращение.
Уточните, пожалуйста, актуальный ли баг?
Какая платформа?

**Comment by goodwin74** [comment]
> @goodwin74 Добрый день, спасибо за обращение. Уточните, пожалуйста, актуальный ли баг? Какая платформа?

Проверил сейчас уже VKWebAppChangeFragment срабатывает в описанном выше случае . Спасибо!
