### ISSUE TITLE
Некорректный текст при вызове метода VKWebAppAddToCommunity

### ISSUE THREAD

**Issue by lightalex** [VKCOM/vk-bridge#43]
В полной версии сайта при вызове метода VKWebAppAddToCommunity отображается некорректный текст:
![image](https://user-images.githubusercontent.com/15173237/74530178-84a00b00-4f3a-11ea-8185-c1775065a6a1.png)
Пользователь будет в недоумении, зачем это приложению нужен доступ к его сообществам. Хотя на самом деле никакого доступа он не предоставляет. Во всяком случае как я понимаю.
В приложении на смартфонах же отображается корректный и понятный текст:
![image](https://user-images.githubusercontent.com/15173237/74530364-e3658480-4f3a-11ea-82ed-aa88429417fc.png)
Надеюсь, что в скором времени такой же текст можно будет наблюдать в полной версии :)

**Comment by danakt** [comment]
Спасибо! Исправим :)

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Поправили
