### ISSUE TITLE
В библиотеке VK Connect отсутствует аналог метода scrollSubscribe из JavaScript SDK

### ISSUE THREAD

**Issue by lightalex** [VKCOM/vk-bridge#44]
В библиотеке VK Connect отсутствует аналог **метода scrollSubscribe из JavaScript SDK**.

Это был полезный метод для использования в полной версии ВК. Если делать правильно и растягивать приложение на всю высоту (как сделан например VK Pay), то возникает проблема центрирования блоков по середине экрана пользователя (именно экрана, не страницы) по высоте. А этот метод отлично выручал в данной ситуации.

**Comment by danakt** [comment]
Спасибо за issue! Вы можете использовать нативную функциональность браузера для этих целей: https://learn.javascript.ru/onscroll

**Comment by lightalex** [comment]
> Спасибо за issue! Вы можете использовать нативную функциональность браузера для этих целей: https://learn.javascript.ru/onscroll

Обращаю Ваше внимание, что данное событие не работает также как scrollSubscribe. 
На видео ниже я наглядно это демонстрирую:
https://youtu.be/okVa56vJDl4
Код:
![image](https://user-images.githubusercontent.com/15173237/74653851-1a85a100-519a-11ea-8ffd-7f5bd0cb59ba.png)

**Comment by lightalex** [comment]
Смысл scrollSubscribe был именно в отслеживании скролла самого ВК (то есть родительского окна), а не скролла iFrame.

**Comment by danakt** [comment]
Думаю, есть смысл сделать такой метод в VKConnect, спасибо :)

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Добавили говорящие события `VKWebAppScrollTopStart`, `VKWebAppScrollTopStop` и `VKWebAppScrollTop`. Документацию для них подготовим чуть позже.
