### ISSUE TITLE
request_id в VKWebAppCallAPIMethod и Promise не ресолвится

### ISSUE THREAD

**Issue by sergiks** [VKCOM/vk-bridge#47]
Если передавать параметр `request_id` в событии `VKWebAppCallAPIMethod`, то возвращаемый Promise **не ресолвится**. При этом событие выстреливает.

Стоит убрать этот параметр, и все в порядке – возвращаемый из `connect.send()` промис ресолвится и далее по цепочке передаётся результат.

Версия vk-connect 1.8.7

**Comment by danakt** [comment]
@sergiks подскажите какой именно метод API вы вызываете. А если это возможно, то напишите код который вы используете

**Comment by sergiks** [comment]
> какой именно метод API вы вызываете.
`groups.get()` с фильтром "admin"

> А если это возможно, то напишите код который вы используете
Код уже сильно изменился, но попробую в ближайшие сутки воссоздать пример, иллюстрирующий проблему.

**Comment by sergiks** [comment]
@danakt вот фрагмент кода, где 6-я строка устанавливает параметр `request_id`. При его наличии, возвращаемый промис никогда не ресолвится. В консоли ошибок нет. Общий слушатель событий при этом по-прежнему получает событие при выполнении этого метода. Но у меня код завязан на промисы. Посмотреть это [приложение](https://vk.com/app7326880) (весь код прямо в странице).

    const getManagedGroups = (access_token) => {
      const result = connect.send(
        "VKWebAppCallAPIMethod",
        {
          method     : "groups.get",
          request_id : Date.now().toString(), // если строку закомментить - работает дальше
          params     :
          {
            filter       : "admin",
            extended     : 1,
            access_token : access_token,
            v            : 5.103,
          }
        }
      );

      return result;
    }

    const getPermissions = () => connect.send("VKWebAppGetAuthToken", {"app_id": APP_ID, "scope": "groups"});

    const run = () =>
      getPermissions()
      .then(
        r => {
          if (!r.access_token) return Promise.reject("No access to groups");
          return getManagedGroups(r.access_token);
        },
        err => console.error("Error getting user token", err)
      )
      .then(
        r => {
          console.log("Got groups:", r.response.items);
          vm.$data.groups.push(...r.response.items);
        },
        err => console.error("Error getting groups", err)
      )
      .catch(err => console.error("Caught error", err))
    ;

**Comment by wolframdeus** [comment]
@danakt Вероятно, можно закрыть в связи с https://github.com/VKCOM/vk-bridge/pull/66
