### ISSUE TITLE
Нет возможности удостовериться что прошла инициализация

### ISSUE THREAD

**Issue by konclave** [VKCOM/vk-bridge#49]
Нет возможности узнать, успешно прошла инициализация или нет. Это нужно для того, чтобы, например, не пытаться стучаться в API когда приложение открыто из Android приложения VK (в этом случае оно открывается просто в окне браузера).

Если вызываешь 
```javascript
vkConnect.send('VKWebAppInit', {})
```
то в ответ не приходит никакое событие. 
Если вызываеть через `sendPromise`, то, соответсвенно, промис повисает в состоянии pending.

**Comment by danakt** [comment]
@konclave в текущий момент идёт работа над ответом в веб-версии (vk.com и m.vk.com) и функциональность скоро будет доступна. В приложениях ответ уже работает, вы можете использовать следующий код:

```js
import connect from '@vkontakte/vk-connect';

connect.send('VKWebAppInit').then(() => {
  // ...
})
```

**Comment by konclave** [comment]
мНу мне как раз нужно обработать случай когда приложение не инициализируется. Поэтому такой вариант не очень подходит. В итоге сделал через запрос информации пользвателся – там приходит ошибка если приложение не инициализированно.

**Comment by danakt** [comment]
@konclave кажется, что это не совсем технически возможно, поскольку общение между приложением и клиентом происходит не синхронно. То есть, приложение отправляет запрос и ждёт пока клиент его обработает. Кажется, что нет кейсов при которых приложение может быть не инициализировано

**Comment by konclave** [comment]
@danakt это случай, когда vk-connect пытается инициализировать приложение вне контекста ВКонтакте. У меня приложение-iframe, на которое пользователи могут попасть не только в контексте ВКонтакта. И в таком случае мне нужно отрубить функционал, связанный с вызовом API VK

**Comment by sergiks** [comment]
@konclave если открыть не в iframe а в браузере, 
в ответ на `connect.send("VKWebAppInit", {});` ловятся два одинаковых события:
`​detail: Object { type: "vk-connect", data: undefined }`

Их нет, если приложение открыто в iframe web-версии ВК.

Вторая мысль – ставить `setTimeout()` по истечении которого считать, что открыт просто-сайт.

**Comment by danakt** [comment]
@konclave спасибо за предложение, думаю стоит реализовать что-то подобное

**Comment by ilyapishchulin** [comment]
Сейчас VKWebAppInit должен нормально резолвить, актуально?

**Comment by ilyapishchulin** [comment]
Закрываю из-за отсутствия активности
