### ISSUE TITLE
GetAuthToken - Unknown error

### ISSUE THREAD

**Issue by tungulin** [VKCOM/vk-bridge#490]
При попытке получения токена по scope - messages. Выдает неизвестную ошибку
<img width="654" alt="image" src="https://github.com/VKCOM/vk-bridge/assets/129746667/b009885f-7a2b-4af3-855d-e3f51b695407">

**Comment by nshvyryaev** [comment]
Здравствуйте! Нужны детали. Какая платформа? Ошибка стабильно воспроизводится?

**Comment by Pronin-vk** [comment]
Доброе утро, поле scope не принимает значение messages
Доступные значения указаны в документации https://dev.vk.com/ru/bridge/VKWebAppGetAuthToken
