### ISSUE TITLE
Метод VKWebAppDownloadFile не работает.

### ISSUE THREAD

**Issue by sorokaIlya** [VKCOM/vk-bridge#491]
Вызываю метод `bridge.send("VKWebAppDownloadFile", {"url": "https://sun9-28.userapi.com/c846420/v846420985/1526c3/ISX7VF8NjZk.jpg", "filename": "test.jpg"});` - на клик пользователя - результата нет.

**Comment by nshvyryaev** [comment]
Здравствуйте! На какой платформе вызываете?

Поддерживаемые платформы:
Android, iOS

**Comment by sorokaIlya** [comment]
Здравствуйте! Я скорее всего понял, в чем дело. Просто в документации не указывается на проблему same origin. Мне приходят изображения с CDN  и скачать не получается даже с download атрибутом. Так как фото с другого сервера то бросает cors error(Access-Control-Allow-Origin ). Получается что проблема только в том что метод VKWebAppDownloadFileResult не бросает Error, a просто зависает

**Comment by nshvyryaev** [comment]
Подскажите, фронтенд приложения где хостится?

**Comment by sorokaIlya** [comment]
Приложение мини апп внутри самого ВК

**Comment by Pronin-vk** [comment]
@sorokaIlya Доброе утро, проблема с зависанием VKWebAppDownloadFileResult еще актуальна?
