### ISSUE TITLE
`VKWebAppOpenApp` is broken

### ISSUE THREAD

**Issue by Pashun4ik** [VKCOM/vk-bridge#492]
According to the documentation, `VKWebAppOpenApp` is meant to be a platform- and direct game/service independent method that  should be able to open any direct game/service.

![image](https://github.com/VKCOM/vk-bridge/assets/18473129/bfd11704-aee0-4abb-93cf-a1dd84f396c0)

But in reality, this method works correctly only within Android (IOS?) application.

For vk.com/m.vk.com it returns `error_data:  {error_code: 5, error_reason: 'Invalid params'}`, if I try to open direct game, but it successfully opens service.

**Comment by nshvyryaev** [comment]
Hello! This method works on web and mobile web platforms for all app types. What app are you trying to open?

PS We can talk in Russian if it is more comfortable for you.

**Comment by Pashun4ik** [comment]
> Hello! This method works on web and mobile web platforms for all app types. What app are you trying to open?
> 
> PS We can talk in Russian if it is more comfortable for you.

Если я в рамках любой игры на m.vk.com/vk.com пытаюсь открыть любую другую игру, я получаю ошибку:
![image](https://github.com/VKCOM/vk-bridge/assets/18473129/a89fdfeb-c7a3-4f63-a738-0099fd501b94)

Но сервис при этом из игры открывается:
![image](https://github.com/VKCOM/vk-bridge/assets/18473129/1af80f66-aca5-47dc-a4ec-e993f299f2f3)

**Comment by nshvyryaev** [comment]
Должны быть какие-то дополнительный обстоятельства - метод работает исправно, я запустил игру из вашего примера поверх елочки (app51748467)
<img width="1664" alt="Снимок экрана 2023-12-13 в 12 53 33" src="https://github.com/VKCOM/vk-bridge/assets/43132141/748f59ff-c632-4a4c-9c4b-6a7db37a28ec">

проверьте вкладку Network на предмет ошибок, вижу Invalid Params может вернуться, если бэкенд отдал не успешный ответ

**Comment by Pashun4ik** [comment]
> Должны быть какие-то дополнительный обстоятельства - метод работает исправно, я запустил игру из вашего примера поверх елочки (app51748467) <img alt="Снимок экрана 2023-12-13 в 12 53 33" width="1664" src="https://private-user-images.githubusercontent.com/43132141/290101829-748f59ff-c632-4a4c-9c4b-6a7db37a28ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTIwMTcsIm5iZiI6MTcwMjQ1MTcxNywicGF0aCI6Ii80MzEzMjE0MS8yOTAxMDE4MjktNzQ4ZjU5ZmYtYzYzMi00YTRjLTljNGItNmE3ZGIzN2EyOGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YWVjMmVlY2NjMGE3NDQ0YjBmODY1ZWQzY2ZlNjNkODhiZGRkOWRjOTYyMTllNjhhMDc2N2FjOTIzZWM1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B5DbhNt-bW5Rw7mllZcVW8GSpbWqISOpfh_zKNBP2DI">
> 
> проверьте вкладку Network на предмет ошибок, вижу Invalid Params может вернуться, если бэкенд отдал не успешный ответ

Вот что содержит ответ
![image](https://github.com/VKCOM/vk-bridge/assets/18473129/635cf9db-d692-4086-ba9a-72970340c8ae)

**Comment by Pashun4ik** [comment]
И тело запроса соответственно
![image](https://github.com/VKCOM/vk-bridge/assets/18473129/61fddcc7-9eb2-4b92-9b50-e2177ff8317c)

**Comment by nshvyryaev** [comment]
Да, действительно, есть ограничение на запуск только мини приложений. Я уточню этот момент и вернусь сегодня

**Comment by nshvyryaev** [comment]
Мы планируем снять это ограничение после новогодних праздников.

**Comment by Pronin-vk** [comment]
@Pashun4ik Добрый день, проверьте актуален ли баг

**Comment by Yarkin13** [comment]
@Pashun4ik убрали ограничения на запуск игра, проверьте пожалуйста
