### ISSUE TITLE
Неверный тип для ответа CreateHashResponse  на событие VKWebAppCreateHash

### ISSUE THREAD

**Issue by quick6response** [VKCOM/vk-bridge#493]
Внутри вместо hash, должно быть sign - об этом нам говорит документация (https://dev.vk.com/ru/bridge/VKWebAppCreateHash#VKWebAppCreateHashResult) и возвращаемый тип ответа на событие 

https://github.com/VKCOM/vk-bridge/blob/c195ceb28e51c4e07ddebf9a349261b571119a73/packages/core/src/types/data.ts#L973-L975

**Comment by nshvyryaev** [comment]
Добрый день.
Действительно, есть несоответствие типов. Забрали в работу.

**Comment by 7lexik0n** [comment]
Добрый день! Поправили типы
