### ISSUE TITLE
Невозможно обработать ошибку POST запроса в photos.saveWallPhoto

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#50]
При вызове метода photos.saveWallPhoto с 1-2 фотографиями - всё в порядке. Но при вызове с 3-6 фотографиями с большой долей вероятности происходит ошибка POST запроса, которую никак нельзя поймать и отработать - ни кетчем у промиса, ни общим try/catch.

Нужно разрезолвить промисс на стороне библиотеки в случае ошибки соединения.

Скрин ошибки в консоли:
![image](https://user-images.githubusercontent.com/49682765/75116984-414e4680-5676-11ea-9c4c-6fdc4b70f61f.png)

Пример вызова:
```
connect.send("VKWebAppCallAPIMethod", {
   "method": "photos.saveWallPhoto", 
   "params": {
      "photo": data.photo,
       "server": data.server,
      "hash": data.hash,
      "group_id": group_id, 
      "v":"5.103", 
      "access_token":token
   }
 });
```

**Comment by ilyapishchulin** [comment]
В документации написано, что не стоит загружать на один урл больше 1 вложения.
