### ISSUE TITLE
[Ошибка] VKWebAppCheckAllowedScopes с "group_messages"

### ISSUE THREAD

**Issue by goodwin74** [VKCOM/vk-bridge#524]
Добавить в VKMA вызов метода VKBridge VKWebAppCheckAllowedScopes с параметром:
{scopes: 'group_messages'}, чтобы убедиться нужно ли предлагать пользователю вызов VKWebAppAllowMessagesFromGroup

При вызове VKWebAppCheckAllowedScopes с параметром: {scopes: 'group_messages'}  получаем client_error - Param scopes should be a...

![image](https://github.com/VKCOM/vk-bridge/assets/15101984/4ae5edd8-cfaf-4cb1-8801-d908600eb543)

В ошибке говорится, что такого права нет хотя он заявлен в доке, как раз чтобы чекнуть возможность отправки оф сообществом сервиса пользователю.

![image](https://github.com/VKCOM/vk-bridge/assets/15101984/ccb74872-9808-40ee-9636-37e1109c694c)

Однако в списке ошибки есть просто "group". Пробуем запустить с  {scopes: 'group'} и выпадает ошибка api_error 100 - One of the parameters specified was missing or invalid: Invalid scopes list

![image](https://github.com/VKCOM/vk-bridge/assets/15101984/ba1db274-17ed-4a0e-b3b2-5dae4bba8deb)

В итоге сервису никак не получается узнать разрешил ли уже пользователь отправку сообщений от оф сообщества сервиса или нет.

**Comment by Pronin-vk** [comment]
Добрый день, проверьте, пожалуйста.
