### ISSUE TITLE
Отсутствует метод для получения высоты родительского окна для полной версии сайта 

### ISSUE THREAD

**Issue by lightalex** [VKCOM/vk-bridge#53]
Хотелось бы, чтобы был добавлен метод, который позволяет узнать height окна РОДИТЕЛЯ iframe'а приложения. То есть чтобы VK предал window.innerHeight приложению, так как это значение не совпадает у самого VK и у iframe приложения.

Это пригодилось бы для адаптирования высоты окна приложения через VKWebAppResizeWindow под размер экрана просмотра пользователя. Так как сейчас данную высоту никак не получить и приходится задавать статичное значение высоты iframe.

**Comment by kuhel** [comment]
Не очень понятно какой use case у этого. Высота родительского окна не нужна, в VKWebAppResizeWindow высота устанавливается чтобы избежать скролла внутри контейнера iframe

**Comment by lightalex** [comment]
Тогда почему у VKWebAppResizeWindow такие жесткие ограничения?
А именно height - может принимать значения от 500px до 4050px.
4050px это довольно мало для больших списков. Особенно в случае использовании подхода "бесконечных списков", например как на странице vk.com/feed .

Use case как раз в том чтобы перенести скролл внутрь контейнера, и таким образом избежать вышеуказанных ограничений в 4050px, но при этом, чтобы окно iframe'а занимало всю высоту экрана пользователя для удобства просмотра. Так как при достижении максимальной высоты в 4050px появляется второй скролл, внутри контейнера, а это просто ужасно...

Тут два варианта решения проблемы:
1) Добавить метод который описан в данном тикете.
2) Убрать ограничение в 4050px.

P.S. Вообще было бы еще не плохо понизить минимальную высоту хотя бы до 200px. Вообще могу сказать, что столкнулся с тем, что при переносе приложения с JavaScript SDK на VK Connect раньше все выглядело просто великолепно, приложение отлично вписывалось в интерфейс ВК. А теперь есть широкая пустая полоса, если интерфейс приложения становится слишком низким (да такие ситуации бывают), либо появляется второй скролл, если интерфейс слишком высокий.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Обновили VKWebAppUpdateConfig, теперь там приходит
