### ISSUE TITLE
[Bug]: ошибка при отправке пустого `scope` в `VKWebAppGetAuthToken` 

### ISSUE THREAD

**Issue by DartVart** [VKCOM/vk-bridge#548]
### Описание

У пользователей android'a при попытке первый раз запустить метод `VKWebAppGetAuthToken`, где на месте `scope` пустая строка, возникает следующая ошибка: 

```json
  "error_type": "api_error",
  "error_data": {
    "error_code": 100,
    "error_msg": "One of the parameters specified was missing or invalid: scopes is undefined",
    "request_params": [
      { "key": "method", "value": "apps.checkAllowedScopes" },
      { "key": "oauth", "value": "1" },
      { "key": "lang", "value": "ru" },
      { "key": "scopes", "value": "" },
      { "key": "app_id", "value": "51859965" },
      { "key": "v", "value": "5.229" },
      { "key": "https", "value": "1" }
    ]
  }
```

Если пользователь перезайдет в приложение, то ошибка не воспроизводится.

### Версия vk-bridge

2.7.2

### Платформа

Android

### Шаги воспроизведения

Метод `VKWebAppGetAuthToken` запускается первый раз на android c пустым `scope`

### Ожидаемое поведение

Возвращался необходимый `access_token`

### Приложение

https://vk.com/vk_temperament

### Код, который вызвал ошибку

```js
const { access_token, scope } = await bridge.send('VKWebAppGetAuthToken', { app_id: appId, scope: '' });
```

**Comment by 7lexik0n** [comment]
Здравствуйте! Уточните, пожалуйста, ошибка воспроизводится при запуске в браузере на телефонах android или в приложении vk на android?

**Comment by DartVart** [comment]
Добрый день! Ошибка воспроизводится в приложении vk на android

**Comment by 7lexik0n** [comment]
Спасибо за информацию! Завели по вашему обращению задачу, передали ответственной команде

**Comment by DartVart** [comment]
На текущий момент также заметили, что у части пользователей android при тех же условиях и в `access_token`, и в `scope` возвращается `undefined`, при этом повторная перезагрузка не помогает. Пример устройства: телефон Galaxy S21 FE 5G, andriod 14-ой версии

**Comment by DartVart** [comment]
Добрый день! На данный момент где-то около трети пользователей, заходящих из-под `android`, получают данную ошибку. Понимаю, процесс устранения багов идет довольно долго, но не могли бы вы дать примерные строки по исправлению?

**Comment by sharipovv** [comment]
У сожалению, пока что мы не можем сориентировать вас по срокам решения ошибки — проблема стоит в очереди на исправление

**Comment by 7lexik0n** [comment]
Добрый день! 
Можете, пожалуйста, дать больше данных о том, как воспроизвести проблему (id пользователя, данные об устройствах, мб видео воспроизведения). Ответственной команде пока что не удалось вопроизвести баг, поэтому по срокам сложно оценить.
