### ISSUE TITLE
dist/index.umd.js ошибка 2.0.3

### ISSUE THREAD

**Issue by goodwin74** [VKCOM/vk-bridge#56]
**vkBridge.send is not a function**

если вывести в консоль объект **vkBridge** - показывается следующая картина:
```
-vkBridge
--applyMiddleware: ƒ e()
--default:
---send: ƒ (o,r)
---sendPromise: ƒ (o,r)
---subscribe: ƒ e(e)
---unsubscribe: ƒ (e)
---supports: ƒ (e)
---isWebView: ƒ ()
```

т.е. функция send и остальные находятся не в корне **vkBridge**, а в объекте **default**

**Comment by danakt** [comment]
@goodwin74 вы подключаете библиотеку на страницу через <script>?

**Comment by goodwin74** [comment]
> @goodwin74 вы подключаете библиотеку на страницу через <script>?

Всё верно. Сейчас работаю на vkconnect 1.7.3 на которой всё стабильно, однако решил сначала  обновится до 1.9 когда еще был vkConnect там такая же ситуация произошла с появлением default, а когда вышла 2.0.3 vkBridge заменил везде vkConnect на vkBridge и в итоге снова этот объект default в котором почему то теперь все функции, ну и естественно выдаётся ошибка что в vkBridge нет функции **send** 

На 1.7.3 vkConnect объект имеет такую иерархию:
```
-vkConnect
--send: ƒ l(e,n)
--subscribe: ƒ c(e)
--sendPromise: ƒ (o,r)
--unsubscribe: ƒ (e)
--isWebView: ƒ ()
--supports: ƒ (e) 
```

**Comment by danakt** [comment]
Спасибо за сообщение! В ближайшее время появится ещё отдельная версия для браузеров, где всё вернётся на места

**Comment by goodwin74** [comment]
> Спасибо за сообщение! В ближайшее время появится ещё отдельная версия для браузеров, где всё вернётся на места

будем ждать! а то приходится сидеть на старой версии :)

**Comment by danakt** [comment]
Используйте новый скрипт: https://unpkg.com/@vkontakte/vk-bridge/dist/browser.min.js
В нём работают как `window.vkConnect`, так и `window.vkBridge`
