### ISSUE TITLE
[Bug]: Метод VKWebAppShowImages с десктопа в bridge. supports возвращает false

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/vk-bridge#560]
### Описание

Что с методом bridge VKWebAppShowImages, он по сути работает с десктопа, а в bridge. supports возвращается false

### Версия vk-bridge

-

### Платформа

Web

### Шаги воспроизведения

-

### Ожидаемое поведение

-

**Comment by Pronin-vk** [comment]
(см https://github.com/VKCOM/vk-bridge/issues/561)
