### ISSUE TITLE
Вызов send('VKWebAppResizeWindow', {height}) возвращает rejected promise

### ISSUE THREAD

**Issue by konclave** [VKCOM/vk-bridge#57]
Вызов метода  `send('VKWebAppResizeWindow', {height: 1500})` из приложения, запусщенного из m.vk.com на мобильном браузере возвращает rejected promise с ошибкой:
```
{"error_type":"client_error","error_data":{"error_code":6,"error_reason":"Unsupported platform"}}
```
При этом `supports('VKWebAppResizeWindow')` возвращает true.

**Comment by danakt** [comment]
Спасибо!
