### ISSUE TITLE
VKPay теряет связь с приложением при работе в мобильной версии сайта m.vk.com

### ISSUE THREAD

**Issue by konclave** [VKCOM/vk-bridge#58]
Запускаю приложение с VKPay в мобильной версии сайта, вызываю окно оплаты VKPay, вызвав `bridge.send('VKWebAppOpenPayForm', params)`. Окно с формой подтверждения VKPay появляется в новом окне. Дальше, если, например, я отменяю платеж, то в окне с приложением я уже не получаю никаких событий и не могу узнать, что там произошло с формой VKPay.

**Comment by danakt** [comment]
Подскажите, наблюдается ли эта проблема до сих пор и какие платформы затрагиваются?

**Comment by konclave** [comment]
Я попробую проверить. Нужно некоторое время.

**Comment by konclave** [comment]
@danakt Да, наблюдается, похоже. В мобильной версии сайта вызов события приводит к открытию формы подтверждения VKPay в отдельной вкладке браузера. И когда я выхожу из формы даже не просто закрыв вкладку, а стрелочкой назад, то вкладка с формой просто закрывается и всё. В основной вкладке ничего не происходит. Ну по крайней мере промис, который вернул метод .send не реджектится и в хэндлер subscribe тоже ничего не приходит касательно Pay. 

Акцентирую внимание, что это на m.vk.com происходит.

**Comment by ilyapishchulin** [comment]
Завел

**Comment by ilyapishchulin** [comment]
Исправили, спасибо
