### ISSUE TITLE
[Bug]: VKWebAppShowStoryBox с параметрами для шеринга с камеры на андроид платформе

### ISSUE THREAD

**Issue by qpounodb** [VKCOM/vk-bridge#582]
### Описание

При вызове метода [VKWebAppShowStoryBox](https://dev.vk.com/ru/bridge/VKWebAppShowStoryBox) для открытия редактора историй с параметрами для использования камеры на андроид платформе, он падает с ошибкой, в описании которой, указана необходимость параметров, которые не требуются по документации.

### Версия vk-bridge

2.15.1

### Платформа

Android

### Браузер и версия

vk mobile app v8.105 (25115)

### Шаги воспроизведения

вызвать метод [VKWebAppShowStoryBox](https://dev.vk.com/ru/bridge/VKWebAppShowStoryBox) для открытия редактора историй с параметрами для использования камеры на андроид платформе

### Ожидаемое поведение

По документации [VKWebAppShowStoryBox](https://dev.vk.com/ru/bridge/VKWebAppShowStoryBox), при установке  параметра `background_type` в заначение `'none'`, не должна требоваться установка параметров `url` или `blob`. 

Редактор историй должен открываться с использованием камеры для создания фона истории, как это происходит в данный момент на платформе IOS.

### Фактическое поведение

на андроид платформе метод [VKWebAppShowStoryBox](https://dev.vk.com/ru/bridge/VKWebAppShowStoryBox), при установке  параметра `background_type` в заначение `'none'` производит ошибку:

```js
{
  error_type: 'client_error',
  error_data: {
    error_description: 'Background type NONE require url or blob',
    error_code: 1,
    error_reason: 'Unknown error',
  },
}
```

### Код, который вызвал ошибку

```ts
try {
  await bridge.send('VKWebAppShowStoryBox', {
    background_type: 'none',
    camera_type: 'front', // или без параметра
    attachment: {
      text: 'vk',
      type: 'url',
      url: 'https://vk.com',
    },
  });
} catch (error) {
  console.error(error);
}
```

**Comment by pasha-nikitin-2003** [comment]
Добрый день! Фикс внесли!

**Comment by qpounodb** [comment]
Спасибо, теперь работает нормально

**Comment by qpounodb** [comment]
Спасибо, теперь работает нормально
