### ISSUE TITLE
Некорректный тип ответа на VKWebAppShowOrderBox

### ISSUE THREAD

**Issue by medvejut** [VKCOM/vk-bridge#63]
По документации status должен быть cancel/success/fail https://vk.com/dev/vk_bridge_methods?f=3.1%20VKWebAppShowOrderBox
В types описан так же, как и в документации:
![image](https://user-images.githubusercontent.com/16665459/75674391-f942ab80-5c95-11ea-8e73-327cafa3af8b.png)

По факту приходит 'charged':
![image](https://user-images.githubusercontent.com/16665459/75674067-5db13b00-5c95-11ea-9314-96ed17ac622f.png)

Приходится обрабатывать таким образом:
```
const result = await this._bridge.send("VKWebAppShowOrderBox", {type: "item", item: orderId)});
const success = <any>result.status === "charged";
```

**Comment by CrazyFlasher** [comment]
Причём по факту это не верно..changed приходит моментально, до того как наш сервер сделал запись.

**Comment by ilyapishchulin** [comment]
Не воспроизвел, подскажешь платформу?

<img width="627" alt="Снимок экрана 2020-07-29 в 11 26 41" src="https://user-images.githubusercontent.com/45998835/88776236-62b7df00-d18e-11ea-9274-2a13580cca02.png">

**Comment by medvejut** [comment]
![image](https://user-images.githubusercontent.com/16665459/88777296-b7a82500-d18f-11ea-94e2-5549db6260ba.png)
Только что проверил - всё так же status = charged. На десктопе (зашел через хром), но в мобильной версии сайта (через m.vk.com/games/app...)

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Должно быть исправлено

**Comment by ilyapishchulin** [comment]
Видимо не актуально
