### ISSUE TITLE
В возможных значениях WidgetType забыли указать donation

### ISSUE THREAD

**Issue by drago-v** [VKCOM/vk-bridge#64]
![image](https://user-images.githubusercontent.com/20705877/75676424-390b9200-5c9a-11ea-8312-8e3cb803ee4f.png)

Собственно, не хватает одного из типов виджета, а именно **donation**

https://vk.com/dev/objects/appWidget_2?f=9.%20Donation

**Comment by danakt** [comment]
Спасибо!
