### ISSUE TITLE
Отсутствует событие вызова модального окна

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#65]
При вызове события VKWebAppGetAuthToken есть три основных сценария развития событий
1. Ошибка запроса = библиотека триггерит событие с описанием ошибки
2. Разрешения уже даны = библиотека триггерит событие с токеном
3. Разрешения ещё не даны = библиотека открывает модальное окно с запросом разрешений, **но не генерирует никаких событий об этом**.

В третьем сценарии отсутствие триггеринга события об открытии модалки - это проблема. 

Опишу юзер кейс:

Важный факт: Приложение имеет настроенную автовысоту (окно приложение подстраивается под высоту содержания в приложении, чтобы не было скролла).
Чтобы загрузить изображение через приложение, нужен токен пользователя. Мы стараемся получать разрешения по мере их необходимости. Поэтому запрашиваем токен только при взаимодействии с блоком загрузки изображений. При запросе токена - модальное окно появляется в самом верху документа, а так как приложение имеет автовысоту и форма внутри высотой в несколько экранов - то появившееся в момент взаимодействия модальное окно не видно (только затемнение) и нужно только догадаться проскроллить вверх, чтобы увидеть модалку.

Как решение - можно делать скроллинг вверх при каждом вызове токена, но тогда получается проблема со вторым сценарием. Если разрешения уже даны - то беспричинный скроллинг 
вверх будет выглядеть странно.

Пока что будем решать через таймер: если в течении секунды нет события от второго сценария - значит было вызвано модальное окно и нужно скроллить вверх. Но это ужасное решение.

Возможные решения:
1. Генерировать событие о вызове модального окна - чтобы иметь возможность отличить  третий сценарий от второго.
2. Сделать метод проверки - существует ли уже на данный момент токен с нужными правами, который можно будет предварительно вызывать перед VKWebAppGetAuthToken 
3. Начать учитывать высоту приложения и позицию скролла, чтобы показывать модальное окно в видимой для пользователя области
4. Сделать контейнер с модальным окном position:fixed, а не position:absolute

**Comment by wolframdeus** [comment]
Речь идет о нативном приложении?

**Comment by KSmokvin** [comment]
> Речь идет о нативном приложении?

Да, верно. О нативном приложении, когда высота фрейма больше высоты экрана и скролл прокручен вниз в момент вызова модального окна.

В мобильной версии и в приложениях всё в порядке, так как там контейнер похоже имеет fixed позиционирование по экрану, а не absolute, как в нативном приложении.

**Comment by wolframdeus** [comment]
Странно, потому что я вот вчера заходил а Giftbox с ПК и там модалка появлялась где-то вверху экрана. Они тоже расширяют относительно контента.

А зачем вообще изменять размер фрейма в нативном приложении? Разве это на что-то влияет?

По сабжу - скорее всего тут не проблема бриджа а разрабов iOS/Android версии потому что я предполагаю что это они эти модалки показывают.

В таком случае позиционирование fixed работать не будет, т.к. оно считается от фрейма, а раз вы его увеличиваете, оно все равно будет где-то там далеко внизу. Тем не менее, как я уже сказал, это скорее всего проблема не бриджа а нативных приложений, но лучше ждать кого-то из ВК.

**Comment by KSmokvin** [comment]
Прошу прощения, сглупил. Речь не о нативном приложении, а о десктоп версии. Высота там изменяется, чтобы избавиться от скролла внутри фрейма и если высота больше экрана и скролл прокручен вниз - то модалка появляется за пределами видимости.

**Comment by wolframdeus** [comment]
Вероятно, решить возможностями CSS проблему не выйдет. Боюсь, что даже костыль который вы хотите написать тоже для решения не сильно подойдет. Объясню почему - операции send асинхронны неспроста. Они отправляют запрос на сервер после чего приходит ответ от сервера и только тогда модалка будет отображена. Предполагаю, что на сервере происходит проверка - а надо ли отображать эту модалку? То есть, к примеру, вы хотите с фронта запросить список друзей и серверу надо понять, спрашивать ли у пользователя это разрешение. Если до этого он его давал, сервер пришлет какие-то данные. Если нет, то попросит отобразить модалку с предоставлением разрешения.

То есть вообще, было бы некорректным спустя какое-то время, если промис выполняется более чем N-ое время скроллить к началу страницу, т.к. возможно пока просто ответ не пришел. Тем не менее, сейчас другого выхода нет. 

Fixed позиционированием проблема тоже не решится т.к. позиционирование происходит относительно текущего фрейма, который в вашей ситуации может быть гораздо больше окна браузера.

Получается что в данный момент пока что единственное хоть какое-то решение - скролл по таймауту.

**Comment by KSmokvin** [comment]
Так в этом и проблема, что на нашей стороне это никак не решить вменяемым образом, поэтому и предлагаю разработчика дополнить библиотеку - генерировать событие открытия модального окна.

По поводу fixed позиционирования кстати - оно поможет, изменение позиционирования родительского контейнера с затемнением у модалки с absolute на fixed - то перекрывает на веб всё окно целиком (а не только фрейм прилоежения), так как контейнер с модалкой рендерится не внутри фрейма с модалкой, а поверх него (и поэтому на него и нельзя повлиять или отловить рендер из приложения). Если ВК изменит позиционирование - это решит проблема. Но первый вариант (генерация события в ответ на запрос - открылась модалка или нет) является оптимальным решением в духе этой библиотеки.

**Comment by kuhel** [comment]
Что насчет того, чтобы смотреть на параметры запуска?
Там есть vk_access_token_settings со списком выданных прав. Если вы запрашиваете токен с правами из списка, то модального окна не будет

**Comment by KSmokvin** [comment]
> Что насчет того, чтобы смотреть на параметры запуска?

Да, пришли к этой мысли и сейчас так и делаем. Но это не на 100% решает проблему. Для некоторых методов нужен токен с пустыми правами. А в этом случае непонятно по vk_access_token_settings  давал ли пользователь уже разрешение или нет.

А с учётом недавно обнаружившейся #75 на vk_access_token_settings  и вовсе полагаться нельзя сейчас.

**Comment by KSmokvin** [comment]
Проблема всё ещё актуальна.
И она абсолютно обесценивает возможность менять высоту окна приложения.

Когда пользователь проскроллил на 2 экрана вниз, а потом приложение затемняется - не все понимают, что нужно проскроллить вверх и увидеть модальное окно.

Теперь вынуждены отказаться от изменения высоты окна в пользу наличия непривлекательного вертикального скролла в приложении. И это на 100% делает бессмысленным наличие возможности менять высоту окна ((

**Comment by ekuizhev** [comment]
Также присоединяюсь к @KSmokvin. Хорошо бы знать о том, давал ли пользователь доступ или нет. Я бы хотел сначала рассказать пользователю зачем нам нужны доступы и как они будут использоваться, а не сразу просить разрешения без объяснений. Тут проблема в том, что если пользователь уже ранее давал права, то и информационную модалку с разъяснениями показывать не надо, а узнать я никак не могу есть права доступа или нет.

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Закрываю из-за отсутствия активности
