### ISSUE TITLE
В методе VKWebAppScroll не работает параметр speed

### ISSUE THREAD

**Issue by Valar353** [VKCOM/vk-bridge#67]
При вызове ``` bridge.send("VKWebAppScroll", {"top": 0, "speed": 600}) ``` скроллится до 0 пикселей, но без анимации, то есть скролл происходит мгновенно, игнорируя параметр speed.

**Comment by wolframdeus** [comment]
Сталкивался с этой проблемой. Пока решения нет, предлагаю использовать [react-scroll](https://www.npmjs.com/package/react-scroll)

**Comment by ilyapishchulin** [comment]
на данный момент исправлено?
