### ISSUE TITLE
Получение пользовательского токена обнуляет разрешение на оповещения

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#72]
Здравствуйте!
Мы придерживаемся рекомендации "запрашивайте разрешения по мере необходимости, а не все сразу и впрок". Но это приводит к обнулению разрешения на оповещения.

Кейс:
1. В процессе использования приложения пользователь даёт разрешение на отправку ему уведомлений.
2. Далее в контексте использования приложения, пользователь получает запрос на доступ к photos. Приложение получает соответствующий токен - но с этого момента notify уже обнулён и у приложения доступ ТОЛЬКО к photos.

При этом VK Bridge не поддерживает возможность получения токена с правами notify (его нет в [списке доступных прав](https://vk.com/dev/vk_bridge_events_7?f=%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F) для приложений). То есть если добавить на втором шаге в запрос scope:"photos,notify" вместо "photos" - то мы получим ошибку.

Выходит, что сохранить **ранее полученное разрешение** на оповещения при получении нового токена - технически невозможно, что доставляет неудобства как для администраторов так и для пользователей.

**Comment by kuhel** [comment]
Спасибо, проверим это поведение

**Comment by kuhel** [comment]
Привет, как-то не получилось воспроизвести, настройки уведомлений не менялись после запросы токена. Возможно есть конкретный кейс и пример?

**Comment by ilyapishchulin** [comment]
Закрываю из-за отсутствия активности
