### ISSUE TITLE
bridge.send не срабатывает из useEffect

### ISSUE THREAD

**Issue by YerinAlexey** [VKCOM/vk-bridge#73]
Здравствуйте!

Если попробовать вызвать любой метод из хука `useEffect`, событие не отправляется на мост. Но если вызвать событие вручную через `window.AndroidBridge.VKWebAppGetUserInfo("{}")` **(из отладчика)**, обработчик, созданный из хука сработает. Пока детальным разбором бага не разбирался. Если будет нужно, предоставлю сниппет.

**Comment by wolframdeus** [comment]
Не уверен что проблема в useEffect т.к. он не накладывает никакие ограничения и никак не влияет на ту функцию которая в него передана. Можете отправить код для воспроизведения бага?

**Comment by YerinAlexey** [comment]
@wolframdeus хорошо. Я завтра днём отправлю

**Comment by YerinAlexey** [comment]
Оказалось, дело было не в бридже. Закрываю issue
