### ISSUE TITLE
Невозможно получить токен на мобильных устройствах (auth_error с пустой информацией)

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#75]
На мобильных устройствах у части пользователей запрос токена приводит к ошибке c пустым кодом и причиной. 

`{"error_type":"auth_error", "error_data": { "error":"", "error_description":"", "error_reason": "" }}`

Уже есть 4 жалобы от разных пользователей. Причём началось это недавно. И условия воспроизведения непонятны - иногда всё-таки срабатывает и возвращает токен у тех, у кого проблемы.

Код вызова:

```
      bridge.send("VKWebAppGetAuthToken", {
        "app_id": vkAppId, 
        "scope": 'photos'
      }).then(data => {
        console.log(data)
      }).catch(data => {
       console.error(data)
      });
```

Отчёт от тестера, где пытались выяснить условия (с видео):
https://vk.com/bug212236 (продукт - https://vk.com/bugs?act=product&id=578)

**UPD:** жалобы есть как от iOS так и от Андроид пользователей. При этом в m.vk.com и на десктопе - у них всё в порядке.

**Comment by KSmokvin** [comment]
Продолжают поступать жалобы от пользователей с разными устройствами.

Составили тест для тестера с прямым запросом токена с разными правами ("", "photos", "friends", "photos,friends")
```
          bridge.send("VKWebAppGetAuthToken", {
            "app_id": 7297645, 
            "scope": scope
          }).then(data => {
            this.process = 'VKWebAppGetAuthToken Promise-THEN data: '+ JSON.stringify(data);
            if(data.scope) this.currentScope = data.scope;
          }).catch(data => {
            this.process = 'VKWebAppGetAuthToken Promise-CATCH data: '+ JSON.stringify(data);
          });
```
Во всех случаях приходит auth_error с пустыми данными об ошибке.
Скринкаст действий пользователя с консольной информацией доступен в этом комментарии - https://vk.com/bug212236?cid=45 (продукт - https://vk.com/bugs?act=product&id=578)

**Comment by KSmokvin** [comment]
Продолжаем исследовать баг в рамках отчёта https://vk.com/bug212236
Наблюдается следующие проблемы в мобильных устройствах:

1. После предоставления прав на уведомления, при перезапуске приложения (и даже после очистки кеша) в vk_access_token_settings не передаётся notify (возможно из-за того, что приложение не перезаписывает scope который "запомнило" раньше, см.п.2)
2. После удаления приложения (которое предполагает сброс всех прав), приложение сохраняет предыдущие права (они передаются в vk_access_token_settings - и приложение не просит разрешение на токен с тем же scope. 
3. Если приложение "намертво запомнило" какой то scope - то оно успешно получает токен при запросе токена с этим scope или пустым scope - но выдаёт ошибку auth_error при попытке получить токен с другим scope.
4. Если удалить мини-приложение - то scope сохраняется, но в некоторых случаях запрос токена приводит к аналогичному поведению как в п.3, а в некоторых случаях - начинает выдавать auth_error - при любом запросе, даже при запросе с пустым scope (несмотря на то, что в vk_access_token_settings есть photos, например, в этот момент).

Описанные проблемы похоже наблюдаются У ВСЕХ пользователей Андроид\Айфон приложений. Просто многие "успели" получить токен с scope, нужным для стабильной работы приложения и у них не возникает проблем на практике. А остальные - не могут получить токет, что обрезает существенную долю функциональных возможностей мини-приложения.

**Comment by KSmokvin** [comment]
На данный момент проблема больше не наблюдается.

**Comment by lebedev42** [comment]
Актуальная проблема наблюдается на Android и iOS

**Comment by REDMEE1** [comment]
[](https://apps.apple.com/ru/story/id1538632801)
