### ISSUE TITLE
TypeScript: Argument of type '"VKWebAppUpdateConfig"' is not assignable to ...

### ISSUE THREAD

**Issue by jellyb0y** [VKCOM/vk-bridge#79]
Argument of type '"VKWebAppUpdateConfig"' is not assignable to parameter of type '"VKWebAppInit" | "VKWebAppAddToCommunity" | "VKWebAppAllowMessagesFromGroup" | "VKWebAppAllowNotifications" | "VKWebAppCallAPIMethod" | "VKWebAppCopyText" | "VKWebAppGetAuthToken" | ... 52 more ... | "VKWebAppSubscribeStoryApp"'.

**Comment by danakt** [comment]
Нужен пример кода, при котором возникает ошибка

**Comment by jellyb0y** [comment]
Пример из доки https://vkcom.github.io/vkui-styleguide/#section-themes
Используем событие VKWebAppUpdateConfig

`bridge.send('VKWebAppUpdateConfig');`

Получаем соответствующую ошибку при компиляции TS
При этом метод отрабатывает, если игнорить ошибку.

**Comment by danakt** [comment]
Компилятор TypeScript подсказывает вам правильно, это событие не отправляется, его можно только слушать. Используйте bridge.subscribe для прослушивания событий.
