### ISSUE TITLE
VKWebAppShowWallPostBox сбрасывает цвет экшн-бара к дефолтному

### ISSUE THREAD

**Issue by shevchux** [VKCOM/vk-bridge#81]
1. Устанавливаю свой цвет экшн-бара

`  vkBridge.send('VKWebAppSetViewSettings', { status_bar_style, action_bar_color });
`

2. Вызываю бокс публикации записи на стене

`
  vkBridge.send('VKWebAppShowWallPostBox', options);
`

На этом моменте цвет экшн-бара изменился в соответствии с темой ВКонтакте. 

3. Закрываю бокс публикации записи на стене. 
4. Bug! Цвет экшн-бара остался в соответствии с темой ВКонтакте.

Ожидаемы результат: После закрытия бокса, вызванного событием VKWebAppShowWallPostBox, цвет экшн-бара восстанавливается.

**Comment by shevchux** [comment]
Проверял в Android приложении

**Comment by ilyapishchulin** [comment]
Не воспроизвел

**Comment by shevchux** [comment]
Исправили в последних версиях/
