### ISSUE TITLE
VKWebAppDownloadFile отсутствует в типизации библиотеки

### ISSUE THREAD

**Issue by daniluk4000** [VKCOM/vk-bridge#82]
Использование VKWebAppDownloadFile не определено в библиотеке, поэтому его использование выдает ошибку Typescript

**Comment by daniluk4000** [comment]
Открыл PR: #83

**Comment by diadkafedor** [comment]
Добрый день.  
Добавьте, пожалуйста,  использование VKWebAppDownloadFile в https://unpkg.com/@vkontakte/vk-bridge@2.4.1/dist/browser.min.js

**Comment by daniluk4000** [comment]
Не знаю, в чем у вас проблема, но вам проще создать новую Issue и описать её там, эту переоткрывать нет смысла, так как связана с по сути синтаксическим сахаром (Typescript)
