### ISSUE TITLE
VKWebAppShare обрезает хэш в мобильной версии

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#85]
В мобильной версии сайта отправка события:

`bridge.send('VKWebAppShare', { link: 'https://vk.com/appXXX#hash' });`

Приводит к отправке ссылки `https://vk.com/appXXX` без хэша.
В клиентах работает корректно.

**Comment by danakt** [comment]
К сожалению, ошибка не воспроизводится. Напишите более подробно шаги воспроизведения проблемы, или пришлите используемый код.

**Comment by DenisNP** [comment]
Подойдёт ли в качестве доказательства приложение, в котором через клиент ссылка отправляется с хэшем, а через m.vk.com ровно в том же месте без хэша?

**Comment by DenisNP** [comment]
Шаги воспроизведения:
1. Открыть https://m.vk.com/app7247755 и создать встречу
2. Нажать под заголовком встречи на кнопку Share и отправить полученную ссылку **в личку** любому пользователю.

На m.vk.com:
Ссылка приходит без хэша

В клиенте:
Ссылка приходит с хэшем

В репозиторий этого приложения могу пустить, если нужно.

**Comment by ilyapishchulin** [comment]
А как сейчас дела?

**Comment by ilyapishchulin** [comment]
Исправлено
