### ISSUE TITLE
Свойство tooltip_text_key игнорируется при отправке истории

### ISSUE THREAD

**Issue by DenisNP** [VKCOM/vk-bridge#86]
Событие `VKWebAppShowStoryBox`, отправка объекта со стикерами, в которых есть кликабельные зоны с типом `action_link`.

```js
{
    action_type: 'link',
    action: {
        link: '...',
        tooltip_text_key: 'Кастомный текст',
    },
    clickable_area: [...],
}
```

Но в Истории по факту при нажатии на стикер отображается слово _Перейти_

**Comment by DenisNP** [comment]
Судя по [примеру](https://vk.com/dev/vk_connect_examples?f=%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80+%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0+story_box) есть подозрение, что у этого свойства заданный список значений. Тогда хотелось бы узнать, какие значения возможны.

**Comment by wolframdeus** [comment]
@DenisNP есть точно значения `tooltip_open_app` и `tooltip_open_post`. То что нужны типы - согласен полностью
