### ISSUE TITLE
[Feature request] Работа wall методов в mini apps

### ISSUE THREAD

**Issue by KSmokvin** [VKCOM/vk-bridge#94]
Добрый день.
Планируется ли добавление поддержки остальных методов работы со стеной?
В частности интересуют методы wall.post, wall.edit и wall.delete. В данный момент они недоступны, так как обычного пользовательского токена (даже с правами wall), похоже, недостаточно для доступа к этим методам, а требуется обязательно токен полученный через standalone app.

Если это ограничение не обусловлено реальной необходимостью, будем очень благодарны, если добавить в Bridge полноценную работу этих методов с обычным пользовательским токеном (или любое альтернативное решение, позволяющее использовать эти методы внутри mini apps).

Для wall.post есть отдельный метод VKWebAppShowWallPostBox - но он подходит только для публикации поста, но к примеру не подходит для одобрения предложенного поста (хотя эта возможность описана в документации метода wall.post, на которую ссылается VKWebAppShowWallPostBox).

UPD: если в VKWebAppShowWallPostBox передать post_id и message - то подтвердить предложенный пост таки можно, но такой в предпросмотре автор такого поста - DELETED.
А вот отклонить пост никак ((

**Comment by KSmokvin** [comment]
Пожалуйста, добавьте возможность использовать wall.delete метод с использованием токена пользователя из мини-приложения. Или вызов AppShowBox на удаление поста. Без этого, как без рук.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Доброй ночи, обсудили и решили, что пока этого функционала можно не ожидать

Спасибо за ишью
