### ISSUE TITLE
[Feature request] Третий параметр options для send

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/vk-bridge#95]
Предлагаю добавить третий параметр в `send` являющийся своего рода набором опций выполнения запроса. Изначально, проблема была в том, что при выполнении запроса некоторые из них могли выполняться долго, а какие-то из них, судя по всему, вообще бесконечно (возникали и такие случаи). Выполнение бесконечное, предположительно, из-за того что пропадает интернет, либо это баг определенных операционных систем. Вообще, выглядело так, будто через postMessage ответ от нативного приложения не приходил. 

На текущем проекте нашлись тестировщики, которые этот кейс воспроизвели и приходится каждый запрос через бридж оборачивать враппером, который выполнял бы запрос с таймаутом. То есть вообще хотелось бы чтобы `send` был функцией вроде `(method: string, params: {...}, options: { timeout?: number; })`.

Если фича имеет место быть, могу кинуть PR.

По поводу того, что бесконечно выполняется запрос напишу отдельный репорт.

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Решили, что такого не будет
