### ISSUE TITLE
Событие при подписке и отписке через кнопку "..." справа вверху экрана

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/vk-bridge#96]
На данный момент внутри приложения нет возможности узнать корректный текущий статус подписки на уведомления пользователя. При запуске приложения статус подписки можно читать из параметров запуска - `areNotificationsEnabled`. Тем не менее при изменении этого параметра приложение никогда не узнает о том, что статус подписки изменился.

Было бы круто, если при его изменении, bridge слал уведомление, типа `VKWebAppNotificationsStatusChanged`

**Comment by ilyapishchulin** [comment]
Передал

**Comment by ilyapishchulin** [comment]
Не актуально
