### ISSUE TITLE
Вопрос по установке темы приложения (VKWebAppUpdateConfig)

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/vk-bridge#99]
При запуске приложения на Android  VKWebAppUpdateConfig либо не срабатывает, либо свойство scheme не существует. (Отловить не получается :( Но факт в том) Тема приложения становится светлой, хотя нативное приложение VK использует темную схему.

При сворачивании и разворачивании приложения схема подхватывается и становится темной.

Вот у меня вопрос, либо я что-то упускаю, либо это фича))

Вот код, который отвечает за установку схемы.

```jsx
import { useEffect } from 'react';
import bridge from "@vkontakte/vk-bridge";

const InstallingTheme = ({ children }) => {

	useEffect(() => {
		bridge.subscribe(({ detail: { type, data }}) => {
			if (type === 'VKWebAppUpdateConfig') {
				const schemeAttribute = document.createAttribute('scheme');
				schemeAttribute.value = data.scheme ? data.scheme : 'client_light';
				document.body.attributes.setNamedItem(schemeAttribute);
			}
		});
	}, []);

	return (children)
};

export default InstallingTheme;
```

**Comment by wolframdeus** [comment]
Попробуйте поставить [eruda](https://www.npmjs.com/package/eruda) и залогать все события приходящие от бриджа. Не забудьте сначала привязать обработчик, а только потом вызывать `VKWebAppInit`. 

Если проблема повторится (конфиг не пришел, либо поля `scheme` нет), то скиньте тот конфиг который приходит, если он приходит вообще.

Пример корректной привязки можно посмотреть [тут](https://github.com/wolframdeus/mini-apps-template/blob/master/src/components/AppRoot/AppRoot.tsx#L125).

**Comment by wolframdeus** [comment]
Судя по коду, представленному выше, неизвестно когда был вызван `VKWebAppInit`. Если он был вызван до того, как `InstallingTheme ` замаунтился, то есть вероятность что в этот временной промежуток событие конфига пришло и по этой причине вы успеваете его отловить, т.к. оно больше не приходит (придет, если нажать на какой-нибудь инпут, например)

**Comment by a1phaZ** [comment]
Возможно у меня проблема с организацией кода, но проблема решилась переносом 
```js
bridge.subscribe(({ detail: { type, data }}) => {
	if (type === 'VKWebAppUpdateConfig') {
		const schemeAttribute = document.createAttribute('scheme');
		schemeAttribute.value = data.scheme ? data.scheme : 'client_light';
		document.body.attributes.setNamedItem(schemeAttribute);
	}
});
```
из рендера компонента в index.js сразу после 
```js
bridge.send('VKWebAppInit');
```

Осталась малозначимая проблема с изменением темы оф. приложения, лечится сбросом кэша. Но не думаю, что кто-то будет постоянно играться с темой, поэтому пофиг) Ишью можно закрывать, спасибо за помощь.

**Comment by wolframdeus** [comment]
@a1phaZ Замечательно. Тем не менее, рекомендую написать перед `send`. 

Issue можете так же закрыть сами.
